### ISSUE TITLE
Howto install 

### ISSUE THREAD

**Issue by joystick666** [jishi/node-sonos-http-api#106]
Hi all, 
Sorry for the noob question, but i could not figure out how to install the sonos http api.

npm install did mit work (find the package)

Cheers

**Comment by jishi** [comment]
It would help if you could clarify what OS you are using and what steps you have tried so far.

**Comment by joystick666** [comment]
I am on debian Jessie on RPI, i tried npm install node-sonos-http-api.
Node.js is installed (4.2.2), and avahi.

**Comment by jishi** [comment]
It isn't published on npm since it isn't a module. You either clone the git repo, or download the source files using the link to the zip archive (https://github.com/jishi/node-sonos-http-api/archive/master.zip), unzip to a folder, then you run "npm install --production" to fetch the dependencies necessary to start it.

Start it by running "npm start" or "node server.js".

**Comment by RickStirling** [comment]
To do it via commandline on a pi:

navigate to where the nodes are installed, usually /usr/local/lib/node_modules

Clone the git repro with
sudo clone git REPRO PATH HERE. You get the path from the Clone Or Download link on the front page.

If you already have it installed, rename the existing folder, then copy your settings.json and presets.json file over.
