### ISSUE TITLE
Feature Request: Start Spotify Playlist

### ISSUE THREAD

**Issue by dbs179** [jishi/node-sonos-http-api#110]
Jishi

Thank you for the awesome work.  I have your project set up on an Pi 2B and working with my Amazon Echo with no problems.  It seems that the playlists function only supports Sonos Playlists.  I generally use Spotify, so the bulk of my playlists are set up there.  I normally don't bother to re-create them in the Sonos Playlists.  I was wondering if it would be possible to play Spotify Playlists directly without re-creating them in the Sonos Playlists?  If not, I can work around it easily enough, but direct playback of Spotify Playlists would be amazing.

Thanks,
Dave

**Comment by NovaGL** [comment]
Have you thought of adding them to the favorites?

**Comment by dbs179** [comment]
I have done both, adding them to favorites as well as adding them to Sonos Playlists.  It isn't a huge deal to do either, but my entire family uses spotify with the family plan.  My kids have their own accounts that I follow on our main account attached to the Sonos, so new playlists are added frequently.  I just have to remember to add them to either favorites or sonos playlists for the API to play them.

**Comment by jishi** [comment]
This is something that isn't easily done at the moment, since most interfacing with Spotify requires access to the SMAPI endpoint that also requires authentication. The authentication info is encrypted in the communication between the controller and the Sonos players, and I have yet to figure out the scheme.

The only possible way that I can see today is using favorites. Of course, if added to favorites, it is then possible to copy the relevant data associated with that favorite, and them remove the favorite again. With that data, it is possible to enqueue that specific spotify playlist, but it is a very coarse route to take. 

It is possible to create separate authentication tokens for Spotify that would be used by this API only, but it is a bit of work to build that infrastructure in order to retrieve them, and requires interaction with the user in charge (as a one time thing)

**Comment by dbs179** [comment]
Jishi,

Thanks for the very through response.  I do very much appreciate your work, it is amazing.  Thanks again and I'll keep on adding favorites and sonos playlists!!!  If it ever becomes possible, that will just be icing on the cake.

Thanks,
Dave

**Comment by julesbike** [comment]
Is there a way to play Spotify radio station

That could be a workaround.

**Comment by jishi** [comment]
I believe that you can add a spotify playlist now using the uri for that playlist, example: 

`spotify:user:avflox:playlist:41FyulxoQpuGlvgU7GqUtr`
