### ISSUE TITLE
Test "http://yourserverip:5005/zones" fails

### ISSUE THREAD

**Issue by mhonard** [jishi/node-sonos-http-api#114]
1. Ok got server.js to run but it starts out with a message "no settings file found, will only use default settings http server listening on port 5005" not sure what to make of this. I extracted all the files contianed in your gitthub download to my root drive (C;)
2. Then I try "http://localhost/zones"(is this the correct IP address? 127.0.0.1 gives the same results) and I get a message from windows asking if I want to save zones.jason. If I respond "open" it says if cannot open the file. if I save, it saves to my downloads and if I open with notepad+++ in contains what appears to be much of the preset code.

Please give me a hand. I appear to be missing something obvious.  Thanks

**Comment by jishi** [comment]
If you receive a file, that means the command is working. Some browsers will output the "json" data directly as text, others seem to download it since it doesn't recognize the announced mime-type. What you are actually seeing is a representation of your current zones and their current state. I'm not sure what you are expecting to see, or how you intend to use it.

If you want to use a more handson example, try using the /RoomName/play or pause urls instead. Of course, writing this in a browser is not the intended use, it's just for easy testing without requiring any special tools or programming knowledge. Most people use these URLs with some home automation tool or homebuilt scripts.
