### ISSUE TITLE
Feature request: Publish to NPM registry

### ISSUE THREAD

**Issue by NovaGL** [jishi/node-sonos-http-api#117]
I think it would be great to be able to do npm install node-sonos-http-api.

It's not that hard to do, but If I did it I think it would be a bit weird

http://www.mattpalmerlee.com/2013/04/23/create-your-first-node-module-and-publish-it-to-the-npm-registry/

**Comment by jishi** [comment]
I understand the convenience this would bring but I'm hesitant of this because of two things:

1. I don't feel like npm is the place for distributing applications like this. It's primary use is to provide libraries and dependencies easily. Some applications do make sense, like nodemon, mocha and other developer related tools, but maybe not this. I would much prefer to allow download (perhaps even with pre-bundled node.js and installed dependencies, no mucking about with git or npm) and perhaps a support forum where users could help other users. 

2. I already have a hard time supporting this. Just in the last two weeks I have seen an increased amount of issues raised regarding how to use this tool, by people that doesn't really seem to be the intended audience. I thinks this is primarily due to echo-sonos, and the nature of that project makes the setup to be overly complex. It should maybe be bundled better, to avoid this kind of confusion.

I have however considered publishing sonos-discovery (the underlying framework on which http-api and the web controller is based), but since I personally hate abandonware, I still feel like I need to commit 100% to maintain it if that is the case. I'm not fully there yet. 

Does this make sense?

**Comment by NovaGL** [comment]
Fine by me, you can close this as it was just a suggestion. Happy to help where I can. Some times you need to give tough love "let me google that for you".
