### ISSUE TITLE
Access Control?

### ISSUE THREAD

**Issue by AlexMaghen** [jishi/node-sonos-http-api#123]
Forgive this somewhat newbie question (and by the way, this API works BRILLIANTLY, thank you!). I want to restrict access to this API with some kind of standard HTTP authentication so that I can expose the API to the Internet without people just messing with it. High security is not necessary, just something basic. What is the best way to do this? Will I have to end up editing your code (which I'd rather not do so that I can keep downloading your wonderful updates) or is there an easy way to put something "in front" of it?

Your help most appreciated and donation for the New Year has been made! :)

Alex

**Comment by okoeth** [comment]
You can easily put an Apache or Nginx in reverse proxy configuration in front of the Node server. The necessary commands / configuration can be found in [this GitHub repo](https://github.com/okoeth/docker-apache2-rp). This repo also includes a Dockerfile so that you could build such a reverse proxy in a Docker container (and maybe Node in another). If you don't want to use docker just look into the Dockerfile and run the commands locally.

**Comment by jishi** [comment]
I have a pull request from a contributor that add support for basic auth just like you want, but I haven't merged it yet since I would like to simplify the configuration a bit. See https://github.com/jishi/node-sonos-http-api/pull/87

Hopefully I will get the time to work on it in the coming weeks, if you don't want to muck around with nginx. Nginx however would give you some more options if necessary. Will close this issue since you can subscribe to the pull request to track the status.

**Comment by AlexMaghen** [comment]
Jimmy -

Thanks again for the response and I apologize for my ignorance about GIT (MUST learn!!!). When you say that there's a "pull request," I'm not sure what that means. When I went to the link you sent me, I saw that there was something I could work with there. Does the fact that you haven't "merged it yet" mean that it's someone else's work on top of yours? If so, I think I'll wait only because I'd like to be able to continue with you as you improve the work you've already done.

It is really quite nice, by the way.

Alex



On Jan 2, 2016, at 1:34 PM, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a pull request from a contributor that add support for basic auth just like you want, but I haven't merged it yet since I would like to simplify the configuration a bit. See #87<https://github.com/jishi/node-sonos-http-api/pull/87>

Hopefully I will get the time to work on it in the coming weeks, if you don't want to muck around with nginx. Nginx however would give you some more options if necessary. Will close this issue since you can subscribe to the pull request to track the status.

-

**Comment by jishi** [comment]
Yes exactly. Someone else has done most of the work, and given me the code so I can merge it into my code base. What I meant was that I intend to merge it, but I just want to make some minor adjustment to it before.

**Comment by AlexMaghen** [comment]
One other question: Have you ever been approached by Sonos? I have some good connections at the top there and the fact that they don't have a formal API is, well, just plain silly, no?

On Jan 4, 2016, at 12:25 PM, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes exactly. Someone else has done most of the work, and given me the code so I can merge it into my code base. What I meant was that I intend to merge it, but I just want to make some minor adjustment to it before.

-

**Comment by jishi** [comment]
Actually, I have. I got a job interview there last year, but it didn't really lead anywhere since the people interviewing me wasn't really informed on why I was there and what I had done and I didn't prepare for that :). Would probably been fun but it's hard to assess what people can contribute with during interviews like that. Anyway, I would've perhaps been forced to quit developing this if I started there, so it might be a good thing for you guys :)

Their official API is the UPnP api, and even though it might not seem "official", it is still a standard. I think the biggest problem with it is it stateful requirement, and it's complex data format (SOAP, XML, and XML within XML, yuck!) which makes it very hard to implement in limited environments. Also, the players are very limited in power (CPU and memory wise) which is probably why they haven't tried to to a higher level abstraction API for integration. You get a lot more flexibility as soon as you add something like a raspberry pi.
