### ISSUE TITLE
Play specific Pandora station

### ISSUE THREAD

**Issue by Connor-Knabe** [jishi/node-sonos-http-api#124]
Would it be possible to play a specific Pandora station? I could add it to my favorites but it would be nice make it dynamic and hit http://localhost:5005/living room/pandora/Tycho to play Tycho radio or whichever station you specify.

**Comment by NovaGL** [comment]
You can't do that as this app does not have direct access to the Pandora API, station ids are taken from there, you can also use presets if you want, I think you can do dynamic presets but not sure how.

**Comment by jishi** [comment]
It's true that it won't be possible to address pandora stations using name. However, it might be possible to do it using the specific Sonos URI that is used using the setavtransporturi action.

Could you explain why this would be better than using favorites? Because of the limitation on favorites allowed or something else?

**Comment by Connor-Knabe** [comment]
Yeah I want to have a website where you can enter a Pandora station and then it will go to Sonos and play that specific station.

**Comment by mauijim68** [comment]
Just out of curiosity.  I was playing a Pandora station.  Told Alexa to pause.  Sonos paused.  

Told Alexa to resume sonos, but it just sits there.  Is there a reason that "resume all" would not resume playing the current source? (if it is pandora)?

**Comment by NovaGL** [comment]
Might be best to ask in the Alexa repo as play pause work fine for me, that's what Alexa should be doing, if you want resume all have you done a timeout

http://localhost:5005/resumeall[/{timeout in minutes}]

**Comment by mauijim68** [comment]
I see the node console throw a Resumeall when the command is issued either via Echo or via a browser but when the paused source is Pandora, no action. If the paused source is the local library (i.e. The Q), it resumes as expected.

**Comment by NovaGL** [comment]
Like I said might be better to ask in the plugin you are using if you aren't using this plugin directly.

I use this and it works perfectly http://localhost:5005/living room/playpause

**Comment by jishi** [comment]
@NovaGL Are you saying that it works for you with Pandora explicitly? Radiostations and playback using the queue behaves a bit differently, even though I don't feel like a pause and play should differ.

**Comment by jishi** [comment]
I will close this because the request is a bit outside of the scope for this software.

Some people here mentioned resumeall and doesn't feel like it does what you guys think it should do. FYI, resumeall is supposed to be used as a secondary call for pauseall, meaning that it will restore the state that was prior to the pauseall call. It's not supposed to be used individually, and is not at all supposed to work as a "play all" command.
