### ISSUE TITLE
Shouldn't dockerfile contain "expose 5005"?

### ISSUE THREAD

**Issue by dolphinkite** [jishi/node-sonos-http-api#144]
Hi,

I may be wrong but since this container is listening on port 5005, shouldn't the dockerfile include the command: "expose 5005/tcp"?

On the other hand, I noticed that even if I don't include `-p 5005:5005` in my run command, the container still works (and listen on port 5005).

**Comment by jishi** [comment]
Yeah, you are right. Normally this is what one would do, but given the complexity if the UPnP protocol, which requires support for connections initiated from both ends, as well as support for multicast traffic, this container requires the --net=host option to work, which I assume that you started it with? Otherwise I would be very surprised that it worked at all.


--net=host makes the container to run with direct access to the host network and it's main IP, as opposed to using a dummy network with iptables rules to forward traffic.
