### ISSUE TITLE
It would be preferable to avoid "custom images" in Dockerfile

### ISSUE THREAD

**Issue by dolphinkite** [jishi/node-sonos-http-api#161]
Looking at the new Dockerfile, I see that the base image is now an image (mhart/alpine-node:5.5) that has been uploaded directly by a user. We don't have access to the dockerfile of that image to know how he  built it. In fact, on that image's page, there are discussion from other users who would prefer to also be able to build the image from scratch instead of pulling an image that we do not know for sure what is contains and how it was built.

I noticed that this image has quite a few stars and been pulled many times; yet, I am uncomfortable pulling images that I can't build from scratch or from an official Docker base image.

My suggestion would be to revert to using an official image as base. The trade-off of using extra MB in space is much better than the security trade-off of not knowing for sure what is in that image.

Would it be possible to change the image?

**Comment by jishi** [comment]
The Docker support isn't really in my roadmap, it was contributed because some people find it easier to use. Since the Dockerfile is merely a few rows, it isn't a big deal to just maintain your own Dockerfile with your own base. 

Docker has quite a few quirks when it comes to supporting applications that rely on multicast, which doesn't make it a great fit, to be honest.

I will probably not switch back because of several reasons, and I feel that the alpine base image seems "serious enough" for this. I do however understand where you are coming from, I just think the benefits outweigh the risk on this one.
