### ISSUE TITLE
Duplicate state infos from webhook

### ISSUE THREAD

**Issue by TimoKorinth** [jishi/node-sonos-http-api#182]
I use your webhook implementation to communicate with another node server and found an issue: If there is a state change on a player in a group, you'll get a notification for each player in the group (which is the expected behavior), but each state is the same (at least for the same player).

**Comment by jishi** [comment]
Yeah, that is expected, since it will send you the state of the coordinator of the group. The reasoning behind it was this:

Using the webhook to update state regarding a certain player in your system, let's say `Living Room`, in an external web page or a screen that is available in your room, then you would want to have the state of `Living Room` regardless of grouping or similar. What is actually played through the speaker, should be the state reported. 

However, player specific state, like volume for instance, should differ. If it doesn't, that is a bug. 

What was your intention with the webhook state data?

**Comment by TimoKorinth** [comment]
Ok, my GUI shows all players and you can select one specific player. As there is also an indication of the playing state for each player (on the right) I have to get information about all available players, even if there is another player selected:
![lcars_sonos_playerv2](https://cloud.githubusercontent.com/assets/11049530/14108075/dfc5a29c-f5bb-11e5-8075-551e8589e08b.png)

**Comment by jishi** [comment]
But I don't really see the problem, for example: 

if Küche is grouped with Wohnzimmer, wouldn't you want Küchen to have the same info as Wohnzimmer? Especially since you don't seem to take grouping into account.

**Comment by TimoKorinth** [comment]
Yes, you are right. That is exactly what I've done right now. I compare the "coordinator" property and not the "uuid" property anymore, but I think there is still one issue with this: The volume control is specific for each player and not the group. Now I think I will get the same value for both, right? Its bound to "selectedState.volume".

**Comment by jishi** [comment]
No, it shouldn't. The info regarding current and next track is taken from the coordinator, but stuff like volume is taken from the player in question. If that is not the case, it is a bug.

**Comment by jishi** [comment]
Closing because of no feedback. Reopen if this is still an issue.
