### ISSUE TITLE
Subscribing to the wrong players

### ISSUE THREAD

**Issue by fountside** [jishi/node-sonos-http-api#257]
Hi, I have installed two Linksys range extenders and since then whenever I run npm start, the program tries to subscribe to the range extenders rather than any Sonos player.  When I switch both Linksys range extenders off, the program will subscribe to a Sonos player.  However, if possible I would like to prevent this from happening by specifying the IP address that the program should subscribe to.  Is that possible currently?  Thanks

**Comment by fountside** [comment]
I should add that both range extenders have audio playing capabilities and therefore must be broadcasting themselves as available audio devices in much the same way as the Sonos players.

**Comment by jishi** [comment]
I guess it is the same devices or similar as this person had:

https://github.com/jishi/node-sonos-discovery/issues/58

Are you running the beta version? I think there should be a fix for it there, where devices lacking  household ID would be ignored. It actually is a faulty behavior of the linksys devices, since we explicitly search for Sonos players, so they should not respond.

Specifically this code https://github.com/jishi/node-sonos-discovery/blob/master/lib/sonos-ssdp.js#L40-L43 should prevent them from being found, unless they are so ill behaving that they would respond that they are the specific device type that we are scanning for (but that would be completely insane)

**Comment by fountside** [comment]
Hi, thanks for pointing out another post where this is mentioned. I am running the latest master (not beta).
I used the household ID in the settings.json as specified in your linked post and that has worked.  Thanks for your prompt reply!
