### ISSUE TITLE
Installing the sonos api on a Synology DS415Play NAS

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#263]
Hi
I have the node.js http api running on a Pi and all working well. I want to move to Synology NAS.
I have node.js v4 installed on my DS415Play.

I think I also need NPM but I have no clue how to install that ?
I also don't know how to install the api. I used all command lines on the pi but dont know how its done with the NAS

Any help would be appreciated ?

Thanks
Frank

**Comment by jishi** [comment]
Hi. Npm is only used for installing the dependencies. If you can install them and then copy the whole folder onto the NAS, it should be fine (don't think there are any compiled dependencies for this, so it should be fine to do on windows and mac as well).

But usually you get npm together with node.js, seems weird that it would be missing.

The hard part is gonna be to run it in the background, and autostart it with the NAS. Not sure what would be the best approach here, maybe someone with a synology NAS can chime in? I did a simple bash script that started the node process and kept restarting it if it crashed, which I started in the background from the "local" service in alpinelinux (similar to rc.local), that might be an option.

**Comment by autofrank** [comment]
Thanks jimmy
Perhaps npm was installed with the node.js on the NAS
how I could check ?

Is docker the only way to run on a NAS
hopefully somebody who has it running on a synology might be able to help..

Thanks again for the api, its been very useful for me...
-Frank

**Comment by jishi** [comment]
There should be a script called npm in the same folder as the node.js
executable iirc.

No, you don't need docker, I would even advise against that since it isn't
designed for it and gives you all kinds of headaches when it comes to
configuration and presets. If you could figure out how to run a shell
script at boot time, you would be all set, then I could provide you with
the necessary scripts.

**Comment by autofrank** [comment]
thanks, I'll take a look and make sure its there ...
I'll also look into how to run a shell script at boot time and get back to you...

**Comment by psmith3** [comment]
I have had it running natively on my Synology in the past and problems occur when you upgrade the NAS to the latest OS, it will wipe everything out. Running it in Docker worked for me the best and I have my presets all in the user folder that persists after upgrades. I also have a startup config that the Synology NAS will call at boot up and also have it restart every 2am. I am behind on the latest updates from Jimmy though. If you go to the docker repository website, you will find my detailed instructions on how to may it all work. Search for psmith node sonos http api.

**Comment by autofrank** [comment]
Thanks psmith3
I'll take a look and see if I can make it work
If all else fails I can continue to run it on my pi :-)

**Comment by psmith3** [comment]
I have had it reliably running in Docker now since last December and have not messed with it since. Have undergone many Synology upgrades and all is still well. At some point I need to update the build on Docker to be the latest version and will at some point. At this point, I have not fixed it since it is not broken:-)

**Comment by autofrank** [comment]
thanks Parker
there are some features in the latest beta from jimmy that I wish to leverage.
I'll do some more reading and see if its worth the effort to get on the NAS or leave it where it is.

thanks again
