### ISSUE TITLE
queue.js doesn't return objects

### ISSUE THREAD

**Issue by DJPicasso** [jishi/node-sonos-http-api#316]
Hi,
I have updated my package with the latest verson of node-sonos-http-api (yesterday).
With the latest version I get a different respond of queue.js:
"old" version: {"startIndex":0,"numberReturned":29,"totalMatches":29,"items":[{"uri":"x-file-cifs: .........
latest version: [{"uri":"x-file-cifs://SM........

The prefix with startindex, numberReturned and totalMatches is missing. Is this correct? If yes, how do I get these infos now?
Best Regards
DJPicasso

**Comment by DJPicasso** [comment]
... or another question:
would it be possible to use the queue.js-file of the older version to get still the objects (startindex etc.)?
Ciao
DJPicasso

**Comment by jishi** [comment]
The reason for this is because you no longer have to take pagination into account. The http api will recursively fetch everything and present the complete result to you, the previous behavior was largely due to the way the Sonos players worked. They would only return at max 600 items due to memory constraints (assumebly) so the http api just mimicked that. 

I thought of this as an improvement, which it probably is unless the consuming device have memory constraints as well. 

It's not possible to take the old queue.js as is, but it would be fairly straight forward to make an optional version of it that worked the way it did before. 

But the question is, do you need it?

**Comment by DJPicasso** [comment]
Hi jishi,
thanks for your quick answer. To be honest, the way I use the package, I need the "totalMatches" object.
I always use the queue in the way /ROOM/queue/5/10.
I have realized my own pagination to not get always all results (although I do not have any memory constraints) and therefore it is necessary to have the totalMatches.

Also I do have some new effects with the state.js 
The old version had the feature:
If there is no image for the track you got:
.....
"radioShowMetaData":"",
"absoluteAlbumArtURI":"",
"streamInfo":"","type":"track"},
.....

With the latest version you do not get the objects (e.g. absoluteAlbumArtURI) , if there is no image.

The way I need it: The interface needs to deliver always the same number of objects, otherwise my API crashes!

Ciao
DJPicasso

**Comment by jishi** [comment]
I'm assuming that you have control over your implementation, and can adjust it accordingly? It is not viable that I would adjust the api to fit your specific need, and I would prefer avoiding properties that are empty if possible. The reason they were part of it was merely because of implementation details, not something that was intended.

The queue length is basically the size of the array returned. Of course, this is sub-optimal if you only want the length, maybe it would make sense to create a custom action to get queue length then? Why the 5/10 request? Wasn't that "start from 5, give me 10 items of the queue"? I need more context of your use case in order to give a good answer.

**Comment by DJPicasso** [comment]
>> I'm assuming that you have control over your implementation, 
>> and can adjust it accordingly? 
Yes, of course but the implementation I realized is more or less a gateway between two applications (your sonos-http-api and a Phyton based application for realizing a GUI for a SmartHome). The behaviour of the Phyton based application is "sometimes and somehow" a little bit static and in some characteristics not very flexible. 

>> It is not viable that I would adjust the api to fit your specific need, 
>> and I would prefer avoiding properties that are empty if possible. 
I agree, it doesn't make sense to adjust it only for specific needs.

>> The reason they were part of it was merely because of implementation details, 
>> not something that was intended.
It's a pity but from technical/development point of view I am "based" on standards and interfaces ... and interfaces should deliver always an identical container of objects (even if individual objects are not always delivered/filled) otherwise in changing the interface there will be always the need to change the implementation - as happened now ... but it is as it is.

>>Why the 5/10 request?
I use the request to get only 10 results starting from a defined track, e.g. /ROOM/queue/5/10 or /ROOM/queue/25/10 or /ROOM/queue/0/10
 Inside my gateway implementation I have created a scrolling-area to be shown within the GUI (10 results). For calculating the (end of the) scrolling-area I definitly need the totalMatches-object.

**Comment by jishi** [comment]
Okay, I hear you. I will not change the behavior of the current queue, but if you put this content in the `actions` folder, and name it `legacy_queue.js` or something:

```
function queue(player, values) {
  var startIndex = 0;
  var count = 500;
  if (values.length == 1) {
    //start index has been specified, keep default count
    startIndex = values[0];
  } else if (values.length == 2 && parseInt(values[1]) > 0) {
    //both start index and count have been specified
    startIndex = values[0];
    count = values[1]
  } else if (values.length > 2) {
    Promise.reject('incorrect queue index or count');

  }
  return player.coordinator.browse('Q:0', startIndex, count);
}


module.exports = function (api) {
  api.registerAction('legacy_queue', queue);
}
```

It will expose a `legacy_queue` action that works the way it did previously. Hope that helps!

**Comment by DJPicasso** [comment]
Hi jishi,
that's great! Thanks a lot! I will try it.
Best Regards
DJPicasso

**Comment by DJPicasso** [comment]
... it works!!!! Thanks!!!!
