### ISSUE TITLE
API & Web Controller on one RPi ??

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#330]
Hi,
Would there be any conflict if I wanted to install the web controller on a raspberry pi that is already running your sonos-http-api

Thanks
-f

**Comment by jishi** [comment]
No, it should be fine. You will need to create a runner (for auto restarting) and a startup job to start at boot, you can copy the approach I used by looking at the approach I took:

/etc/local.d/http-api.start
/flash/apps/runner/start_http_api.sh

When you add or modify files outside of the /flash folder, you need to persist changes by calling `lbu_commit`, otherwise they will be lost when rebooting (since it runs from a RAM drive).

**Comment by autofrank** [comment]
- Hi

With regard to 

When you add or modify files outside of the /flash folder, you need to persist changes by calling lbu_commit, otherwise they will be lost when rebooting (since it runs from a RAM drive).

Can I add it within the /flash folder or do I have to install it outside that folder ?

thanks
-f

**Comment by jishi** [comment]
You can add anything you want to the /flash folder. But, if you want it to autostart, you need to put stuff in /etc/local.d or change stuff in /etc, that was what I was referring to.

**Comment by autofrank** [comment]
understood - thanks

**Comment by autofrank** [comment]
web controller up and running :-)

thanks
-f

btw - do you have any plans to add some more functionality
Specifically I'd be interested in he ability to select a line in or a playlist ?

**Comment by jishi** [comment]
To the web-controller? Haven't had time to focus on it in a long time. Those features are fairly trivial to fix, but first and foremost it must be updated to utilize the latest version of sonos-discovery which requires some work.

**Comment by autofrank** [comment]
thanks
...just sent a suggestion to your gmail.

-f
