### ISSUE TITLE
query on Line in and leave

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#334]
Firstly.. thanks for adding the features and I have a question to clarify

**Line In**
My Sat Box is physically connected to my Hallway player as a Line in source
if I want to select that sat Box as a source for my kitchen player do I use

Hallway/linein/Kitchen

Is the first player in the url string the player that has the physical line in connection and the second player in the url is where you want that line in source to play ?

**Leave**
If I select Hallway/leave 
will this leave the group that it was a part of and stop what is playing ?

Thanks
-f

Sorry forgot - which release has the line in and leave support ?

**Comment by jishi** [comment]
The latest master have line-in support, leave has been there since before the beta. 

If you want playback in kitchen, you should first isolate the Kitchen player:
`/Kitchen/leave`
The rest of the group will continue playback if it was playing. 
Then, you tell Kitchen player to use line-in of Hallway player:
`/Kitchen/linein/Hallway`

`/Kitchen/linein` is a shortcut, if you want playback from the local line-in, meaning Kitchen line-in on Kitchen player.

**Comment by autofrank** [comment]
thanks 
I'll pull the latest master 

-f
