### ISSUE TITLE
Problems with clip and say commands

### ISSUE THREAD

**Issue by dolphinkite** [jishi/node-sonos-http-api#349]
Hi,

Thanks for adding the "clip" command, it will be great for my doorbell.

A few comments:
1- In the documentation for the clip command, you cut and pasted "say" and "sayall" but it should be replaced by "clip" and "clipall" instead.

2- When using the clip command, it takes 15 seconds AFTER the audio clip finished playing for the command to complete. That's a long time if I want to queue commands when there is someone at the door. My setup is quite simple, 3 Connect groupes in 2 zones.. Is there a way to "analyse" (or understand" where that 15 seconds is spent and how I can improve it significantly?

3- The "say" command doesn't work for me (it used to, months ago). I did register my key and a file does gets downloaded from voicerss, but it is a text file that contains the message: "ERROR: The language does not support!". I tried using en-fr, en-us and en-ca - none work. 

Thanks

**Comment by jishi** [comment]
How long is the clip? There seems to be certain length that confuses the timing occasionally, because it need to first realize that it started playing the clip, and then realize that playback stopped before reverting. For the single player clip and say command, I have a 30 second grace period that would restore it if nothing happened (not for clipall/sayall though). This be the culprit. If you could run it with debug logging on, it would tell something about what it does. I have also added some more debug logging in the latest master version, I suggest you run that one when testing. To run with debug logging enabled, do (for MacOS and Linux):

`NODE_LOG_LEVEL=debug node server.js`

For windows:
`$env:NODE_LOG_LEVEL='debug'`
`node server.js`

Also, if you could provide the clip that gives you trouble, then I could test to see if I get the same issues as you. I can not replicate it on my system. 

en-fr is not a valid language (what was your expected language for that language code? fr-ca would be canadian french, fr-fr regular french), but en-ca and en-us should be. I just tested it, and it works fine for me. If you haven't tried cleaning out the tts folder of old files, that would be a start (maybe it cached your phrases during some outage?).

**Comment by dolphinkite** [comment]
Haaaaaaaaaaaaaaaaaaaaaaaa. The clip is just a doorbell sound, so it is less than 2 seconds... or so I thought. Turns out, it lasts about 12 seconds. I trimmed the mp3 and everything is back to normal. Sorry for wasting your time.

For the say command, I wrote en-fr but I was actually using fr-ca. I just tried `curl "http://192.168.x.x:5005/say/5-%20Loft/hello/en-us"` and the music stops and restarts but the clip is never played. When looking at the tts directory (which I emptied) I see one file named 46c13axxxxxxxxxxxxxxxxxxxxxxxxxxx0a452edf5-hello.mp3 (I changed the number for the "x") and that file is actually a text file that states "ERROR: The language does not support!"

It used to work (in a very old version over a year ago). I'm confused at what could be the problem.

**Comment by jishi** [comment]
But you are invoking the commands in the wrong order... it's

`/ROOM/command/options/more options`

So in your case:

`/5-%20Loft/say/hello/en-us`

It tried to apply say command to last known player, and use "5- Loft" as phrase, and "hello" as language code (and ignore the "fr-ca"). It became apparent on the filename, since the last part of the file should be language code :)

**Comment by dolphinkite** [comment]
facepalm!
