### ISSUE TITLE
Group Speakers

### ISSUE THREAD

**Issue by csteenwyk** [jishi/node-sonos-http-api#36]
Hi,

Would it be possible to add a way to group 2 or more speakers together and play simultaneously?

Something like
/[controller]/add/[additional_node]
/controller/remove/[additional_node]

Or is there another easy way to do it?

**Comment by jishi** [comment]
Hi, it is possible today (although not as straight foward as one would like), by invoking:

/PlayerName/setavtransporturi/x-rincon:[UUID of coordinator player]

This becomes kind of backwards of course. I'm thinking that it should work like this:

Invoke action "group" on any player that is part of a group (or standalone), send in the room name of the player that you want join with that group.

The other option would be, call action "join" on the player that you want to join to a group, and send in the room name of any player of the group you want to join. 

Which do you think makes more sense?

**Comment by matiasgarciaisaia** [comment]
Nice idea :)

I think the best way is to imitate what you would do on the Sonos Controller interface: you pick the group that's playing, and add/remove a room to it. So, if I have a room called Playing and I want to attach a room Joining to it, I'd like to call `/Playing/add/Joining` (and `/Playing/remove/Leaving`).

But if there's not that much overhead in offering the other way round, too - `/Joining/join/Playing` and `/Leaving/leave` - that would be OK, too.


I won't promise anything, but this seems something I could implement if I come with a few spare minutes - but if you want to do this, great :)

**Comment by jishi** [comment]
@matiasgarciaisaia feel free to send me a pull request, it will take a while before I have time to look at this.

**Comment by ewaucq** [comment]
Hi, I'm struggling on grouping/de-grouping my sonos components using the http api. I tried to look for examples with no luck.

Basically I'm using presets.json to group 2 components using 
{ "party_mode": { "players": [   { "roomName": "kitchen", "volume": 25}, {"roomName": "living room", "volume": 35} ] }
and it works like a charm.

How can I ungroup my components so I end up with 'kitchen' and 'living room' separated again?
I tried to create 2 other presets in presets.json but I always end up with a syntax error at server startup.
I guess there is a simple way to send a few http requests but I just cannot figure it out...

Thanks for your help and thanks for your great work !

**Comment by csteenwyk** [comment]
I also like the idea of mimicking the way the Sonos app works. I think that
interface would be great.

**Comment by matiasgarciaisaia** [comment]
@jishi, I've tried this:
```
var _api;

function addToGroup(player, values) {
  var joiningPlayer = _api.discovery.getPlayer(decodeURIComponent(values[0]));
  joiningPlayer.coordinator.setAVTransportURI(player.avTransportUri);
}

module.exports = function (api) {
  _api = api;
  api.registerAction('add', addToGroup);
}
```

But `setAVTransportURI` seems to be not working. I also call it via the browser like `http://localhost:5005/default/setavtransporturi/x-rincon-queue:RINCON_000E58C0565401400%230`, and it gets to the `setAVTransportURI`, but doesn't group the rooms.

Am I missing something?

**Comment by jishi** [comment]
To start with, grouping uses "x-rincon:" as url scheme. "x-rincon-queue:" is for reactivating the queue on a player / coordinator after you have switch to radio for instance.

Secondly, I think it's backward. "joiningPlayer" is the one you want to add to the group, right? That means that you would need to:

joiningPlayer.setAVTransportURI("x-rincon:"  + player.coordinator.uuid)

The AVTransport of the group coordinator will not have the correct uri, but all the other members would. It would be more difficult to find another member that isn't coordinator than to just compose the uri yourself. 

Also add a null check after getPlayer, to handle an invalid roomName, otherwise it will crash. And, a player has a reference to discovery as well, so you don't needto store the reference to api, you can just use player.discovery if you like.
