### ISSUE TITLE
General question queue / trackseek / playlist

### ISSUE THREAD

**Issue by DJPicasso** [jishi/node-sonos-http-api#376]
Hi,
I have a general question regarding starting a track from a queue.

1.  I start a playlist on my Sonos Player (e.g. http://<ip-adress>:5005/Office/playlist/Charts2016)
The player starts with the 1 track (everything is fine)

2. With http://<ip-adress>:5005/Office/queue I will get the queue of the playlist

3. With http://<ip-adress>:5005/Office/trackseek/5 I can "jump" to the 5th track and it starts playing (everything fine)

4.  I now start a radio station from my favorite list 
(http://<ip-adress>:5005/Office/favorite/<my_radio_station>)
The player starts with the radio station

5. With http://<ip-adress>:5005/Office/queue I will still get the queue of the playlist, which means, the queue of my earlier playlist is still valid

My question: How do I restart now the tracks of my queue?
E.g. http://<ip-adress>:5005/Office/trackseek/5 doesn't work any longer, even if the queue is still valid.
Is there another possibility to start one of the songs of my queue?

Best Regards
dj.picasso

**Comment by jishi** [comment]
The approach that works for now is to set the avtransport to the queue-uri:

/PlayerName/setavtransporturi/x-rincon-queue:[UUID of said player]%230

"%23" is the # sign, but it needs to be url-encoded. 

However, it probably makes sense to automatically switch to queue playback when you try to invoke trackseek, instead of erroring out. I'll think about it.

**Comment by DJPicasso** [comment]
Thanks for the answer, it works!
