### ISSUE TITLE
use swagger file to control actions

### ISSUE THREAD

**Issue by antxxxx** [jishi/node-sonos-http-api#384]
Have you considered having a swagger document to describe the endpoints? I know you are using swagger-ui to provide a gui to show a nice page to try out the api, but looking at this you have hard coded the definition in static/docs/index.html rather than reading from a swagger file   

 If you do have a swagger file, you can then use a framework like swagger-restify-mw or swagger-express-mw which uses the swagger file to control how the api behaves - ie if you want a new endpoint you add it to the swagger document and your documentation is updated and the new endpoint is automatically exposed - you just need to write the code to implement it, so you no longer need to read all files in lib/actions directory to work out the actions available.   

It also means it is easy to expose endpoints using different http verbs - eg you could have endpoint /zones/{zoneName}/queue and call GET to see what is in the queue, DELETE to clear the queue, PATCH to add something to the queue and POST to replace the queue - although this would obviously be a breaking change to current behaviour.

**Comment by antxxxx** [comment]
I realised this might make more sense with an example, so I have created a quick POC implementing what I have described. Its at on the swagger branch at https://github.com/antxxxx/node-sonos-http-api/tree/swagger. You can run it by doing an npm install and running app.js. It is currently set to serve on port 10010

The swagger file is at api/swagger/swagger.yaml and I have implemented all the endpoints - although all except get all zones and get individual zone return a not implemented yet error.    

You can get the swagger file when it is running by calling http://localhost:10010/swagger. This also means you can use swagger-ui to load the swagger file, so I have updated the static/docs to have the latest swagger-ui only changing index.html to load http://localhost:10010/swagger instead of the petstore example. This can be accessed at http://localhost:10010/docs/ when running

**Comment by jishi** [comment]
I'm familiar with swagger-controlled API implementations, using hapi and swaggerize-hapi at work. I however built this long before that, and the swagger-ui addition was done as a contribution and I haven't maintained it very well. 

Although I agree that combining documentation and implementation is a good idea, I also need to consider the trade offs in terms of ease of use, maintainability and the ability for people to contribute. Basically I have had a few main points that I have tried to stick with:

* As few dependencies as possible
* Easy testability in a browser (this is the reasoning behind the GET scheme)
* Logical to figure out how it works for non-programmers

Of course I have run into some restrictions because of this, GET scheme isn't really a good fit for certain commands, and impossible for some requested features. Documentation is also poor, and downright wrong in some places. However, much of it is mitigated by the simplicity of the url scheme for now.

I appreciate the suggestion, and it is a very valid suggestion. I might eventually go down that route, but I also have the ambition to allow easy modification and contribution from people that aren't as experienced and I think adding swaggerized routes and some massive REST framework could work against that.

**Comment by antxxxx** [comment]
Those are valid points. I work with swagger all day too and I sometimes forget that not everybody is as familiar with it as I am and it does add an extra dependency that might put some people off.   

I am however going to continue implementing it on my fork using swagger - mainly because I really want the ability to add and delete from the queue using a REST API rather than SOAP.  This is for my own benefit on some other integrations I am working on, but I am happy to share my code.   

I am happy to rename my fork if you prefer to avoid confusion with your project. I will also of course give full credit to you for the initial excellent idea and most of the code, and include a link back to this project

**Comment by jishi** [comment]
It will be interesting to see the end result. But as you suggested, maybe renaming the fork to not cause confusing could be a good idea, since they will stop being compatible. 

I'm closing this for now since it isn't an actual issue. Please reach out when you have implemented the full suite, then I can have a look at it. 

Cheers!
