### ISSUE TITLE
JSON repeat state is changed in latest version from "true/false" to 3 states "none, all, ?"  

### ISSUE THREAD

**Issue by Home-Control9000** [jishi/node-sonos-http-api#397]
Hi Jimmy,

In the JSON state output the repeatstate was in my production version true or false. With new version it seems that it has 3 states: "none, all, (1 track?)" 
Can i set now the repeat for 1 track, all tracks or none. In the docs i cant find anything concerning this.
Thanks.

**Comment by jishi** [comment]
The HTTP API is not updated to support all three cases, but uses the legacy true/false which maps to all/none for now.

The underlying code however, supports it. I just haven't fixed it yet. Basically the 
`return player.coordinator.repeat(values[0] == "on" ? true : false);`

could take "all", "one" or "none" as argument instead of true false, I believe.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

I have test it.  
curl http://linux7:5005/woonkamer/repeat/off
curl http://linux7:5005/woonkamer/repeat/on
Is working and the JSON repeat state is:
'none' or 'all'
Would be great if we can use:
curl http://linux7:5005/woonkamer/repeat/none
curl http://linux7:5005/woonkamer/repeat/one
curl http://linux7:5005/woonkamer/repeat/all
and that the JSON represent the same state like none, one, all
For now i will change my mappings in my api.

Thanks.
Walter

**Comment by jishi** [comment]
It now supports "none", "one", "all". "on" and "off" still maps to all/none for legacy reasons.
