### ISSUE TITLE
Problems with absolute URL for albumArtURI

### ISSUE THREAD

**Issue by Markkuuss** [jishi/node-sonos-http-api#40]
I have problems with absolute URL for albumArtURI. Since this is implemented, the API does not work anymore. Each time the URL ist called the IP address and the port is rewritten in the URL.

1st call - result:

"currentTrack": {
"artist": "",
"title": "x-sonosapi-stream:s14991?sid=254&flags=32",
"album": "",
"albumArtURI": "http://192.168.86.101:1400/getaa?s=1&u=x-sonosapi-stream%3as14991%3fsid%3d254%26flags%3d32",
"duration": 0,
"uri": "x-rincon-mp3radio://br_mp3-bayern3_m.akacast.akamaistream.net/7/442/142692/v1/gnl.akacast.akamaistream.net/br_mp3_bayern3_m"
}

2nd call - result:

"currentTrack": {
"artist": "",
"title": "x-sonosapi-stream:s14991?sid=254&flags=32",
"album": "",
"albumArtURI": "http://192.168.86.101:1400http://192.168.86.101:1400/getaa?s=1&u=x-sonosapi-stream%3as14991%3fsid%3d254%26flags%3d32",
"duration": 0,
"uri": "x-rincon-mp3radio://br_mp3-bayern3_m.akacast.akamaistream.net/7/442/142692/v1/gnl.akacast.akamaistream.net/br_mp3_bayern3_m"
}

3rd call:
"albumArtURI": "http://192.168.86.101:1400http://192.168.86.101:1400http://192.168.86.101:1400/getaa?s=1&u=x-sonosapi-stream%3as14991%3fsid%3d254%26flags%3d32",

And so on.

This happens especially when the URL is called within short intervals.

**Comment by jishi** [comment]
Yeah, that doesn't look right :) Obviously the state object that is received is not a copy, but a reference in here:

https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/state.js

Meaning that I modify the underlying state when fixing the albumArtURI. This would be reset every 15 seconds or when a change occur otherwise.

Once option would be to expose them separately, .albumArtURI and .absoluteAlbumArtURI instead. That way it could copy it for every state request, from the unmodified .albumArtURI. I see that you forked it, if you want to try it out, send me a pull request if you change it and make it work.

**Comment by jishi** [comment]
I added an absoluteAlbumArtURI instead, which shouldn't suffer from this behavior.
