### ISSUE TITLE
Jingle before say command

### ISSUE THREAD

**Issue by rhalbheer** [jishi/node-sonos-http-api#400]
I have to say, I tried but failed.....
Would it be possible to add a jingle before SONOS talks? My wife complains that she will get a heart attack otherwise :-)
I had it in an older version, that I added a jingle before I added the tts stream but in this version I cannot get it working (the two streams are always mixed).
Thank you
Roger

**Comment by jishi** [comment]
There is no "real" way of doing this today, and the workaround becomes a bit clunky. What you could do is:

/pause
/clip/jingle.mp3
/say/your announcement
/play

which would effectively do what you are asking. The pause/play is there because after clip has finished, it would still restore system and you probably don't want music to resume until after the announcement. Do note that if system was paused already, it would start playing again, so preceeding this with some sort of state check would be preferable. 

The "correct" way of implementing this would be to either jolt a jingle together with the announce soundfile (quite complex), or create a 2 track playlist that we can wait for to finish. It would be possible to do this while maintaining the queue, but haven't looked at it, and you are the first one to request this.

**Comment by freeyland** [comment]
I would also like to have this functionality 👍
