### ISSUE TITLE
resumeall & pauseall don't always work

### ISSUE THREAD

**Issue by Burnett2k** [jishi/node-sonos-http-api#401]
Steps for me to reproduce:

1. start Sonos http server
2. type into my browser localhost:5005/zones and verify that it shows my sonos play 1 setup as master room. Everything seems in order
3. type into my browser localhost:5005/resumeall because the sonos is currently in the paused state after playing a spotify playlist
4. Instead of the usual success return code it shows [] and that's it. In the STD out, it says 'resuming all players' when I type in the resumeall command, but nothing happens.

I have attached the STDout which doesn't supply much information.

Additional info. If i go and hit play on the sonos, the commands usually start working so I wonder if it is some sort of sleep timer that is going off and not allowing it to receive commands. Is there another command you need to run to wake up the machine?

Let me know if you need any other information.

[stdout.txt](https://github.com/jishi/node-sonos-http-api/files/641102/stdout.txt)

**Comment by jishi** [comment]
I think this functionality might be a bit confusing. pauseall/resumeall works in conjunction with eachother. This means, that resumeall only works correctly if you have first called pauseall, since it will remember which player it actually paused, and only resumes the players it paused. 

Just calling resumeall shouldn't do anything, since it hasn't been responsible for the pausing. 

Does this explain your behavior?

**Comment by Burnett2k** [comment]
That does make more sense now. I realized last night that I could instead call /play & /pause on that specific room and it seemed to work every time. (http://localhost:5005/living room/pause, etc.).  I guess I was confused because I assumed if the player was in a paused state already that hitting resumeall would start it playing again.  So, you have to call a pauseall before you call a resumeall??  I would expect it to attempt to resume no matter what happened previously.

**Comment by jishi** [comment]
If you consider this use case:

Phone is ringing. I want to pause the system so that I hear my phone and doesn't disturb me while talking. 

I hang up. The system should restore the previous state. 

That was what I needed, hence I didn't want to blindly just start playing every player that had some music source loaded. As you said, you can blindly invoke play against all players and you get the behavior you expect, although I agree that the naming of these action sort of indicates that it should just resume everything. pausesystem/resumesystem might had been a better naming scheme.

**Comment by Burnett2k** [comment]
I see. That makes sense. I'll try and mess around more with the system next time before posting a noob question. Thanks!
