### ISSUE TITLE
setavtransporturi example

### ISSUE THREAD

**Issue by robmathieson** [jishi/node-sonos-http-api#41]
Hi all

Does anyone have an example of the SetAVTransportURI REST request working? I'm trying to load a particular mp3 file from a location on the server, but its just not happening. Suspect my URL structure is wrong, but I'm pulling my hair out.

Many thanks.

Rob

**Comment by robmathieson** [comment]
HI all, still need some help with this. I'm using the following call:

http://localhost:5005/kitchen/setavtransporturi/C%3a%5ctest.mp3

to get a file at location c:/test.mp3

Am i missing something here?

**Comment by jishi** [comment]
Hi!

You need to send a URL that is understandable for Sonos. The easiest is to expose the mp3 through a web server, and then use that URL. There is a builtin webserver in the http-api that you could juse for it. If you drop the file into th static folder (or a subfolder inside static), you can point to it using:

http://ip-address:5005/file.mp3 or http://ip-address:5005/subfolder/file.mp3

please note that you need to use the IP-address of your machine when you are sending it to Sonos, since it will need to fetch it over your network.

Of course, you need to url-encode it accordingly.

**Comment by robmathieson** [comment]
Hi Jishi

I've tried all different combinations of this with no luck. Apparently there is a third parameter that possibly needs passing (CurrentURIMetaData). I've tried looking into you code, but its a bit beyond me unfortunately.

The last example of my URL is:

http://localhost:5005/kitchen/setavtransporturi/http%3a%2f%2f192.168.0.14%3a5005%2f50.mp3

which is forr the file location:

http://localhost:5005/50.mp3

I have checked that location through a browser and it plays fine.

**Comment by robmathieson** [comment]
ignore the localhost, I was using the IP Address.

http://localhost:5005/kitchen/setavtransporturi/http%3a%f2%f2192.168.0.14%3a5005%2f50.mp3

**Comment by robmathieson** [comment]
As a test, I set the default file for my webserver to be that mp3, there for it would play if anyone hit that location. I have passed this url to the action and it still fails. Definitely think there must be another param to add.

**Comment by jishi** [comment]
Hi again, I have now managed to test this and notice that there is a missing decode of the parameters that broke it. I have fixed it and pushed an update, hop this helps.

**Comment by robmathieson** [comment]
Brilliant, thank you so much. :)

Rob Mathieson

**Comment by jokull** [comment]
For anyone with issues here ... Sonos was giving me an error although album art and metadata was showing up. Turns out the URL should not have encodeURIComponent - it's handled by the library. So try that if you're having issues. Seems like the album art *can* have encoding for URI components however.
