### ISSUE TITLE
raspberry pi 3 npm start  issue

### ISSUE THREAD

**Issue by harmelgill** [jishi/node-sonos-http-api#414]
Hi , sorry if i am being  naive 

i get this error when starting npm  o
raspberrypi:~/sonos/node-sonos-http-api $ uname -a
Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux
pi@raspberrypi:~/sonos/node-sonos-http-api $ 

pi@raspberrypi:~/sonos/node-sonos-http-api $ npm start

> sonos-http-api@1.2.1 start /home/pi/sonos/node-sonos-http-api
> node server.js

npm ERR! sonos-http-api@1.2.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.2.1 start script.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.34-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/sonos/node-sonos-http-api
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by jishi** [comment]
Does it start with
nodejs server.js

If the apt version of nodejs is not version 4+ it won't work. I suggest you
install node.js manually if that is the case.


On 21 Dec 2016 01:03, "harmelgill" <notifications@github.com> wrote:

Hi , sorry if i am being naive

i get this error when starting npm o
raspberrypi:/sonos/node-sonos-http-api $ uname -a
Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l
GNU/Linux
pi@raspberrypi:/sonos/node-sonos-http-api $

pi@raspberrypi:~/sonos/node-sonos-http-api $ npm start

sonos-http-api@1.2.1 start /home/pi/sonos/node-sonos-http-api
node server.js

npm ERR! sonos-http-api@1.2.1 start: node server.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.2.1 start script.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node server.js
npm ERR! You can get their info via:
npm ERR! npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.34-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/sonos/node-sonos-http-api
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jishi/node-sonos-http-api/issues/414>, or mute the
thread

**Comment by harmelgill** [comment]
Hi Sorry to trouble

this is in the log file

 info it worked if it ends with ok

1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]

2 info using npm@1.4.21

3 info using node@v0.10.29

4 verbose run-script [ 'prestart', 'start', 'poststart' ]

5 info prestart sonos-http-api@1.2.1

6 info start sonos-http-api@1.2.1

7 verbose unsafe-perm in lifecycle true

8 info sonos-http-api@1.2.1 Failed to exec start script

9 error sonos-http-api@1.2.1 start: `node server.js`

9 error Exit status 1

10 error Failed at the sonos-http-api@1.2.1 start script.

10 error This is most likely a problem with the sonos-http-api package,

10 error not with npm itself.

10 error Tell the author that this fails on your system:

10 error     node server.js

10 error You can get their info via:

10 error     npm owner ls sonos-http-api

10 error There is likely additional logging output above.

11 error System Linux 4.4.34-v7+

12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"

13 error cwd /home/pi/sonos/node-sonos-http-api

14 error node -v v0.10.29

15 error npm -v 1.4.21

16 error code ELIFECYCLE

17 verbose exit [ 1, true ]

**Comment by jishi** [comment]
You have node 0.10.x, that will not work. Uninstall it via apt-get and get
the official binaries from nodejs.org

**Comment by harmelgill** [comment]
Thank you will do that
