### ISSUE TITLE
How were the Fuse library search parameters determined?

### ISSUE THREAD

**Issue by mdanderson99** [jishi/node-sonos-http-api#420]
I am trying to improve the search on my music library and am new to Fuse but I think I understand how it works.  I am wondering how the parameters were chosen and what trade-offs were found specific to the API's response time and accuracy when applied to artist / track / album searches.  It seems the parameters have been the same since the first commit (threshold: 0.2, distance: 5, maxPatternLength: 100).  But if I understand Fuse correctly, why choose "5" for the distance?

If I were more adept at JS I'd figure out how to inspect the results of the search and play with the parameters myself... may have just convinced myself to learn :)

**Comment by jishi** [comment]
@jplourde5?

**Comment by jplourde5** [comment]
I played around with the settings until I started getting good results.  It could very well be that the parameters could be refined more. Let me know if you come up with some better settings and we can adjust the standard settings.  We can also add the parameters to the settings.json file if we find that they need to be tuned for different libraries by some.

**Comment by ppitkin** [comment]
@jplourde5: I played around with them quite a bit. It turns out that these settings are probably a really good compromise given the wide spectrum of results that need to be handled. I found I could tune then to get better results return for a particular request but then it would be worse for other requests. 
If you take a looks at that code that I sent you a while back you will see that I refine the returned results a bit more.  This gave me a really high hit rate. 

@mdanderson99: just be aware that there are limitation when using the Sonos library as the source. Its generally OK if you are just asking for tracks but if you work with albums like I do then it is not very good (can't have multiple albums with the same name for example).
Its for that reason that I developed an extension to jplourde5's great work which allows the scanning of an external file system to build the FUSE search library or the use of an external mySQL database instead of FUSE. Combined this with an Amazon echo skill the searching is nearly as good as asking for Alexa to play something directly from the amazon music library.

**Comment by mdanderson99** [comment]
Thank you all!

@ppitkin Please tell me more.  The search has been working fairly well now, but I do typically just work with tracks.  If I understand the current implementation correctly, a library is already built up in http-api for FUSE and then that's what's searched on given the keyword from the Alexa skill?  Or are you doing the search at the Alexa level, with it's (obstensibly better?) search algorithms, then returning that specific hit to the http-api?
