### ISSUE TITLE
AWS TTS Polly problems

### ISSUE THREAD

**Issue by rodders99** [jishi/node-sonos-http-api#421]
I've generated the keys VoiceRSS keys and everything works as expected. 

I want to use the AWS Polly voice and have followed the instructions, as well as attaching access policy in IAM and edited settings.json accordingly, but I am getting the error message that an API key is required. 

Am I missing something obvious ? 

Thanks

**Comment by jishi** [comment]
Sounds like you are not running the latest version. What version does your package.json say? 

You also need to remove any alternative configurations for other voice providers, just keeping one since it cannot guarantee the preferred order of things. Meaning, remove voicerss configuration from settings.json, if you want to use AWS Polly.

**Comment by rodders99** [comment]
Yep that was it, I only downloaded a few weeks ago ! 

Thank you.
