### ISSUE TITLE
Replace + with %20 in say command

### ISSUE THREAD

**Issue by tnemrap** [jishi/node-sonos-http-api#424]
Many urldecoders replaces space with + instead of %20.
When using say then it reads up plus.

/Mike

**Comment by jishi** [comment]
It's because I use decodeURIComponent() for decoding the value. This is, according to my findings, the "correct" approach, and "+" as space delimiters is only valid for requests that has Content-Type application/x-www-form-urlencoded, and only in query string parameters and/or POST form data. 

If they replace space with "+", it is not a urlencoder per definition, but rather a form value encoder. Both encodeURIComponent()/decodeURIComponent() and escape()/unescape() will treat plus chars literally. 

For PHP you have http://php.net/manual/en/function.rawurlencode.php which actually does the correct thing (opposed to `urlencode`). I suggest you try and find a better urlencoder :) Do you have an example of a broken one? In which language do you do this?

**Comment by jzajac2** [comment]
I'm trying to figure out how to use the sayall function with a rails app using uri's open, for example

```
uri = URI.parse(URI.encode("#{HOST}:#{PORT}/sayall/#{speak_what}"))
response = open(uri).read
```

```
Here's an example request with a 302:
Request URL: http://localhost:3000/text_to_speech?utf8=%E2%9C%93&text_to_speak=kyle+go+to+sleep
Request Method: GET
Status Code: 302 Found
```

I'm assuming I have to URI.encode it otherwise I get 

`URI::InvalidURIError (bad URI(is not URI?): myhost:5005/sayall/go to sleep)
`
There are other methods:
```
Addressable::URI.parse
CGI::escape
HTMLEntities.new.decode
```

However since sayall uses decodeURIComponent(), I don't know what I need to do to get the request through in a raw format similar to what a browser will accept (with spaces), which seems to be necessary for sayall, correct?

I may have to resort to javascript `XMLHttpRequest` I had that working fine, having hard time mapping what that does to the 'railsy' way. 

Any suggestions?
