### ISSUE TITLE
Presets File with Playbar Sound from TV

### ISSUE THREAD

**Issue by NSEchris** [jishi/node-sonos-http-api#441]
I'm trying to use the preset file to group my "Kitchen" speaker with the "Family Room" playbar with audio coming from the TV.  Since the audio is already playing through the playbar from the TV, I'm only looking to add the "kitchen" to the group and set the volume.

I tried setting up the preset file without a favorite specified, but when I start the service, it doesn't show that it loaded the preset when looking at the terminal output.

Is there a way to do this?

Thanks for creating this tool!

**Comment by jishi** [comment]
Shouldn't be a problem, could you paste the preset content you are using? Have you checked the logs? It would give a warning if it could not parse the JSON and ignore the file.

**Comment by NSEchris** [comment]
Here is the present content:
{
  "players": [
    {
      "roomName":"Family Room",
      "volume": 30
    },
    {
      "roomName":"Kitchen",
      "volume": 40
    }
  ],
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": false
  },
  "pauseOthers": false,
  "favorite": "My fav"
}

One definite problem is that I don't have a favorite called "My fav", but I'm also not trying to play a favorite since I want to group the kitchen speaker with the playbar which is already outputting the TV's sound.  I also created a file called test.json omitting the "favorite": line, which you will see failed to load when I started the service up, stating a parse error at position 317.
<img width="780" alt="screen shot 2017-01-19 at 12 43 53 pm" src="https://cloud.githubusercontent.com/assets/25226504/22118285/201c5bf2-de45-11e6-8392-119b5910d6ba.png">

I have the node running in a VM of Ubuntu 10.04.  I'm a linux n00b, so I don't yet know how to look through the log files, or where they are at, but I'll see if I can figure it out.

Thanks again for your help!

**Comment by jishi** [comment]
You probably forgot to remove the trailing comma when you removed the
favorite. Run it through an online json validate / linter to verify syntax.

You can omit any values from the presets that you don't want to change,
like playmode, volume and stuff like that.

Or you could just join kitchen with Family room directly

/Kitchen/join/Family Room


On 19 Jan 2017 6:52 PM, "NSEchris" <notifications@github.com> wrote:

Here is the present content:
{
"players": [
{
"roomName":"Family Room",
"volume": 30
},
{
"roomName":"Kitchen",
"volume": 40
}
],
"playMode": {
"shuffle": true,
"repeat": "all",
"crossfade": false
},
"pauseOthers": false,
"favorite": "My fav"
}

One definite problem is that I don't have a favorite called "My fav", but
I'm also not trying to play a favorite since I want to group the kitchen
speaker with the playbar which is already outputting the TV's sound. I also
created a file called test.json omitting the "favorite": line, which you
will see failed to load when I started the service up, stating a parse
error at position 317.
[image: screen shot 2017-01-19 at 12 43 53 pm]
<https://cloud.githubusercontent.com/assets/25226504/22118285/201c5bf2-de45-11e6-8392-119b5910d6ba.png>

I have the node running in a VM of Ubuntu 10.04. I'm a linux n00b, so I
don't yet know how to look through the log files, or where they are at, but
I'll see if I can figure it out.

Thanks again for your help!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jishi/node-sonos-http-api/issues/441#issuecomment-273847981>,
or mute the thread

**Comment by NSEchris** [comment]
Thank you, works perfect!!  I didn't realize I could use the "join" between rooms, which is exactly what I was trying to do.
