### ISSUE TITLE
Return current state for new functionality

### ISSUE THREAD

**Issue by maddox** [jishi/node-sonos-http-api#472]
We can now control the Sonos Sub, but we can't get it's state.

Right now, `GET /:zone_name/sub` now returns: 

```json
{"message":"Valid options are on, off, gain, crossover, polarity"}
```

It'd be great if this returned the different values of the sub like this:

```json
{
  "on": true,
  "gain": 4,
  "crossover": 2,
  "polarity": 3
}
```

Additionally, a `GET /:zone_name/speechenhancement` and `GET /:zone_name/nightmode` should both return if they are currently enabled or not. 

```json
{
  "on": true
}
```

**Comment by jishi** [comment]
But that's not have other action work, so it would not conform to the previous expectation. Sub state is actually part of the `/zone_name/state` if you have a sub. 

I should add speech anhancement and night mode to the state as well though.

**Comment by maddox** [comment]
Oh ok! That works then. Understood.

**Comment by NovaGL** [comment]
So how do I currently find out if night mode is on? It would be great if it was in the state if it is a playbar

**Comment by maddox** [comment]
> I should add speech anhancement and night mode to the state as well though.

Gentle nudge to get this in there ❤️

**Comment by NovaGL** [comment]
Yay, will try tonight

**Comment by jishi** [comment]
Please report back if this works for the PLAYBAR since I don't own one myself.

**Comment by maddox** [comment]
will try tonight.

**Comment by maddox** [comment]
It's there! Thanks for this.

**Comment by NovaGL** [comment]
Awesome work. It only took you a year to add this functionality in but I am happy none the less. :D

**Comment by jacobwtyler** [comment]
Any plans to add nightmode and speech enhancement for the new Beam? The commands don’t seem to work for it currently.

**Comment by jishi** [comment]
@jacobwtyler There is nothing filtering those call for a certain types of player, it will just blindly try to send it and return an error if it is not supported. 

If it indeeds support it, I would expect it to work, otherwise I would need some trace logs when making the call to pinpoint the problem. Please open a new issue for it, to not notify all on this issue when replying.

**Comment by jacobwtyler** [comment]
One caveat: turning night mode on seems to turn speech enhancement off and visa versus. They don’t seem to be mutually exclusive as I can turn them both on at the same time with the Sonos app. Is this anything fixable?

**Comment by jishi** [comment]
It is the same kind of call but with omitted values for the other
attributes. Maybe the default is off if omitted, then I would always have
to supply the current value (but seems dumb). Can anyone confirm if the
playbar behaves the same?

Might be a bug in the beam firmware otherwise. Regardless, it would be
fixable since I know the state of the other settings.
