### ISSUE TITLE
Strange Response from API

### ISSUE THREAD

**Issue by igen27** [jishi/node-sonos-http-api#495]
Hey guys..i completed the whole setup. Lambda and the Skill are without errors, port forwarding on FritzBox works, the server is reachable over a DynDNS service, Node.js 4.5 on my QNAP A453 is running and "npm start" sets up the server without any error. But i get a strange response when i test locally on http://my.server.domain:5005/zones and the same response by sending the request via my Dyndns Domain:

<img width="1413" alt="bildschirmfoto 2017-05-08 um 21 33 04" src="https://cloud.githubusercontent.com/assets/11257148/25845448/31cd7934-34ae-11e7-9aad-e080757aaf97.png">

Can anybody catch up, where this come from and how must look a correct response? Alexa sends the request but nothing happens on my Sonos.

**Comment by jishi** [comment]
The response for that call is correct. It's a JSON payload describing your zones. 

You would be better off looking at the output of the process on your QNAP, after you have invoked an Alexa skill, since I'm not sure what you are actually testing.

Also, looking in the lambda logs in AWS might be helpful.

**Comment by igen27** [comment]
Thx for the quick reaction, Jishi..so i will search further on my QNAP. I was confused by the response because i had expected only a simple list of the zones or rooms ;-) thanks for your great work and greetz from germany
