### ISSUE TITLE
Get current volume

### ISSUE THREAD

**Issue by shadi1989** [jishi/node-sonos-http-api#503]
Hello,

I cannot find a way to get the current volume value from my Sonos group.
For as far as i found out, only controlling of the volume is possible while i want the current value.
I need it to display it in a webpage i'm building as a wrapper

**Comment by jishi** [comment]
You have two different options:

* fetch volume as part of the state (`/RoomName/state`) and parse out the volume. 
* configure a webhook that would post volume changes to another endpoint

The latter makes it very easy to export the data to an external web page that isn't on the same local network, and also reduces load since it would only trigger on volumes changes, rather than every time you want to inspect the volume.
