### ISSUE TITLE
webhook help

### ISSUE THREAD

**Issue by jmorris644** [jishi/node-sonos-http-api#522]
## Before you submit an issue

I have unsuccessfully tried to enable the webhook. I have tried adding it to the settings object and I have tried it in its own area in settings.js.

In each case startup fails.

Can I get a little more detailed instructions where to put the webhook in the settings.js file?

Thanks

Joe

**Comment by jishi** [comment]
Like it says in the readme, create a `settings.json` file that you put in the root folder (the same one that has a package.json), which has the following content:
```
{
  "webhook": "http://localhost:5007/"
}
```

Replace the url with the actual webhook that you want, or run the `test_endpoint.js` file like this: `node test_endpoint.js` which would recieve webhooks and print them out on the above URL.

Also provide the output generated when startup fails, otherwise it is impossible to tell what error your are observing.

**Comment by jmorris644** [comment]
I am so sorry. I had placed the code in settings.js and not settings.json

All is good now.

BTW, @jishi , did you get my email a little while back?

Joe

**Comment by jishi** [comment]
No, nothing about an email ring any bells... What did it concern?

**Comment by jmorris644** [comment]
I don't see a way to PM you.

Maybe I had an old email.

**Comment by jishi** [comment]
Send me an email at jimmy at shimizu.se
