### ISSUE TITLE
Playlist Not Found - Spotify

### ISSUE THREAD

**Issue by mikenolet** [jishi/node-sonos-http-api#532]
I am having issues playing a playlist.  I have supplied my spotify creds in the settings.json file.  When I make a call to a playlist  by using 

`http://localhost:5005/bedroom/playliat/spotify:user:spotify:playlist:37i9dQZF1DX6VdMW310YC7`

or

`http://localhost:5005/bedroom/playliat/Chill%20Tracks`

The following is returned:

`{"status":"error","error":"Playlist not found","stack":"Error: Playlist not found\n    at /home/hass/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithPlaylist.js:13:15\n    at process._tickDomainCallback `

My settings.json File:
`{
	  "spotify": {
	    "clientId": "myid",
	    "clientSecret": "mysecret"
	  }
	}`

Is there a method to verify if the spotify auth is working?

**Comment by jishi** [comment]
The playlist command is only useful for sonos playlists, not Spotify
playlists.

If you want to play a Spotify playlist, you need to use the Spotify
command.

/roomname/spotify/now/spotify:user:spotify:playlist:37i9dQZF1DX6VdMW310YC7
<http://localhost:5005/bedroom/playliat/spotify:user:spotify:playlist:37i9dQZF1DX6VdMW310YC7>

On 14 Jul 2017 5:40 PM, "Mike" <notifications@github.com> wrote:

I am having issues playing a playlist. I have supplied my spotify creds in
the settings.json file. When I make a call to a playlist by using

http://localhost:5005/bedroom/playliat/spotify:user:spotify:playlist:
37i9dQZF1DX6VdMW310YC7

or

http://localhost:5005/bedroom/playliat/Chill Tracks

The following is returned:

{"status":"error","error":"Playlist not found","stack":"Error: Playlist not
found\n at /home/hass/node-sonos-http-api/node_modules/sonos-
discovery/lib/prototypes/Player/replaceWithPlaylist.js:13:15\n at
process._tickDomainCallback

Is there a method to verify if the spotify auth is working?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jishi/node-sonos-http-api/issues/532>, or mute the
thread

**Comment by NathanMaton** [comment]
I'm in the same boat as Mike. Would love a way to check if the Spotify auth worked or some troubleshooting help. I created an app, copied the example settings.json file into a new file, saved it in the root, added my credentials and tried to play my playlist here: https://open.spotify.com/user/nmaton/playlist/4ZNh6qxRNFnNqkqqs1mFpA

I tried these two strings based on my interpretation of your syntax above:

#1
http://localhost:5005/living%20room/spotify/now/spotify:user:spotify:playlist:4ZNh6qxRNFnNqkqqs1mFpA

Output on page:
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/Users/nmaton/Code/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n    at Player.addURIToQueue (/Users/nmaton/Code/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:596:15)\n    at promise.then (/Users/nmaton/Code/node-sonos-http-api/lib/actions/spotify.js:37:33)\n    at <anonymous>"}

#2 - this one seemed less right.
http://localhost:5005/living%20room/nmaton/spotify:user:spotify:playlist:4ZNh6qxRNFnNqkqqs1mFpA

Output on page:
{"status":"error"}

Thanks!

**Comment by NathanMaton** [comment]
Nevermind. Worked with this: http://localhost:5005/living%20room/spotify/now/spotify:user:nmaton:playlist:4ZNh6qxRNFnNqkqqs1mFpA

**Comment by NathanMaton** [comment]
thanks!
