### ISSUE TITLE
Play Spotify song on all zones

### ISSUE THREAD

**Issue by dennusb** [jishi/node-sonos-http-api#536]
Hi,

The Spotify integration is working great, also the searching is epic. But you NEED to specify a room name, and i would like to play it on ALL zones.
Could something like /all/spotify/now/<trackid> be made available?

**Comment by jplourde5** [comment]
You have to group all of the zones together in order for that to work. It would have to be implemented where specifying "All" as the room would issue a group command first, followed by what ever is being asked for. This would need to be true for all commands where it makes sense, for construct. 

May be better to just issue the start Sonos command and issue whatever you want to do in sequence.

**Comment by jishi** [comment]
The recommended way of doing this would be to use a preset first, and then start the spotify playback. 

Presets can also be applied dynamically, however they do not support spotify sources for the time being, so that wouldn't really help. 

The upside with presets is that you can also apply preferred volume, which is advisable since just grouping them all together usually gives you unexpected behavior, especially for line-in zones that usually defaults to 50% volume when switching to line-in.
