### ISSUE TITLE
Error when trying to node server.js - Synology

### ISSUE THREAD

**Issue by mr-istian** [jishi/node-sonos-http-api#55]
When trying to node server.js i get det following error
Synology> node server.js
no settings file found, will only use default settings
module.js:338
    throw err;
          ^
Error: Cannot find module '/volume1/Multimedia/Sonos/lib/actions/'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requirePath (/volume1/Multimedia/Sonos/node_modules/require-fu/lib/index.js:14:22)
    at /volume1/Multimedia/Sonos/node_modules/require-fu/lib/index.js:21:9
    at Array.forEach (native)
    at fuDirectory (/volume1/Multimedia/Sonos/node_modules/require-fu/lib/index.js:20:34)
    at /volume1/Multimedia/Sonos/node_modules/require-fu/lib/index.js:25:5
    at new HttpAPI (/volume1/Multimedia/Sonos/lib/sonos-http-api.js:28:24)

The folder actions does exist in the place mentioned, and it is containing several files with commands XXXXX.js.

The Node version that is running is as follows 0.12.0-0009. 
I downloaded the node-sones-http-api as zip file, transferred from my mac to synology and unpacked before running npm install (works fine) and then typing node server.js in the correct directory. This was all done while being connected to the synology via terminal ssh on my mac.

**Comment by jishi** [comment]
That is weird. It seems like it tries to load the actual directory, which somehow indicates that it tries to load a module that has an empty string for name. There might be some issue with the node.js version for the synology. Could you please tell me which permissions the actions folder and the residing files get, and what user that tries to invoke it? Maybe invoking "id" or "echo $USER" on the command prompt.

**Comment by mr-istian** [comment]
The action folder has root root and so has al other residing files. The user that is trying to invoke is also root. I am quite new to using terminal, could you specify in regards to invoking "id" er "echo $USER".... I dont know what that means/does?

**Comment by jishi** [comment]
Well, I'm out of ideas for now. It is probably a bug or discrepancy in the way file system traversing is handled on the synology, since the error message indicates that it tries to load an unnamed module (js-file). 

This could either be because `__dirname` isn't handled correctly, or maybe because `var actionsDir = __dirname + '/actions';` doesn't have a trailing slash? Hard to tell without having the tools to reproduce the error. I think other people have been able to install this on their Synology NAS though, or maybe it was just the web controller.
