### ISSUE TITLE
Syntax error on the last pull

### ISSUE THREAD

**Issue by rafale77** [jishi/node-sonos-http-api#562]
/home/xxx/node-sonos-http-api/lib/presets-loader.js:13
  let files;
  ^^^

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/xxx/node-sonos-http-api/lib/actions/clippreset.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

Seeing something to do with strict mode. Not sure how to fix this

**Comment by rafale77** [comment]
found the fix:

Need to add

` "use strict";`

at the beginning of the presets.loader.js

**Comment by autofrank** [comment]
Hi,
I also had an issue with the latest build and had to add "use strict" on the presets.loader.js to get it to run but it still had issues. It is not stable and the 
I  am running it on Pi 2 model B.
It is generating a set of errors on npm start
![npn start screenshot](https://user-images.githubusercontent.com/20369477/31939122-5a1d0cc4-b8b1-11e7-9fb6-200a66a9da39.PNG)

I have attached two npm-dump files, one for when I ran node v4.5.0 and one for when I ran v4.0.0
I also noticed that if I used node v4.0.0 it gave a warning looking for v4.5.0 (see attached screenshot)
node v4.5.0 - https://nodejs.org/dist/v4.5.0/node-v4.5.0-linux-armv7l.tar.gz
node v4.0.0 - https://nodejs.org/dist/v4.0.0/node-v4.0.0-linux-armv7l.tar.gz

![4 0 0 warning](https://user-images.githubusercontent.com/20369477/31939114-52ec09a0-b8b1-11e7-9a07-187a08237b4b.PNG)

I also tried node v6.11.4 it generated errors similar to what was reported in [552](https://github.com/jishi/node-sonos-http-api/issues/552)

Could you review and see how best to resolve
for now I'll downgrade to 1.43 to get back to a stable revision
[npm-dump 4.5.0.txt](https://github.com/jishi/node-sonos-http-api/files/1410458/npm-dump.4.5.0.txt)
I tried to upgrade graceful-fs to the latest but it didn't resolve the issue

Thanks ...

**Comment by jishi** [comment]
@autofrank The log output doesn't give me anything useful unfortunately. I'll need to run some more tests on a rpi, is this a Rasbian install? 

If you have the ability to check out previous commits from master, to see were I broke it, that would be helpful. 

I'm gonna setup some Travis test runs so I avoid these rookie errors in the future :)

**Comment by autofrank** [comment]
Hi @jishi 
Yes, It's a Rasbian install....

The problem wasn't there with 1.43 (99% sure) so I like to start there 
If you can show me how to check out previous commits that would be great and I can try and step up through the revisions to see where it changed 
I assume all revisions should support node.js v4.0.0 up .. correct?
Any min revision for npm ?

Thanks

**Comment by jishi** [comment]
If you have gotten the source code via git, just see the list of commits here: https://github.com/jishi/node-sonos-http-api/commits/master

then copy the "hash" at the right for a certain commit, and run `git checkout xxxxxxxxx` 

Starting with `b0efea0e95b8e77854365dee982597a959e38fd7` is probably a good spot, that's before the most recent stuff, and committed as 1.4.5 (but I didn't tag it).

**Comment by rafale77** [comment]
What do you mean by unstable? I am not having any issues but I am running on ubuntu. Not an RPi.

**Comment by autofrank** [comment]
I haven't had a lot of time to test last night but the say command didn't seem to working as it should. Also the install had a good many errors and warnings even though it worked 
I should know more over the next couple of days and will report back... 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: rafale77 <notifications@github.com> Date: 24/10/2017  16:04  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] Syntax error on the last pull (#562) 
What do you mean by unstable? I am not having any issues but I am running on ubuntu. Not an RPi.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rafale77 in #562: What do you mean by unstable? I am not having any issues but I am running on ubuntu. Not an RPi."}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/562#issuecomment-339021924"}}}

**Comment by autofrank** [comment]
Thanks I 'll try that 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jimmy Shimizu <notifications@github.com> Date: 24/10/2017  15:00  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] Syntax error on the last pull (#562) 
If you have gotten the source code via git, just see the list of commits here: https://github.com/jishi/node-sonos-http-api/commits/master
then copy the "hash" at the right for a certain commit, and run git checkout xxxxxxxxx
Starting with b0efea0e95b8e77854365dee982597a959e38fd7 is probably a good spot, that's before the most recent stuff, and committed as 1.4.5 (but I didn't tag it).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jishi in #562: If you have gotten the source code via git, just see the list of commits here: https://github.com/jishi/node-sonos-http-api/commits/master\r\n\r\nthen copy the \"hash\" at the right for a certain commit, and run `git checkout xxxxxxxxx` \r\n\r\nStarting with `b0efea0e95b8e77854365dee982597a959e38fd7` is probably a good spot, that's before the most recent stuff, and committed as 1.4.5 (but I didn't tag it). \r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/562#issuecomment-339000087"}}}

**Comment by autofrank** [comment]
Hi @jishi 
Not terribly familiar with GIT, just barely enough to get by  
I would normally use git	clone	https://github.com/jishi/node-sonos-http-api.git to pull the latest to my pi
What would the equivalent if I wanted to pull  1.45

**Comment by autofrank** [comment]
Okay - good news
I checked with release 1.43 and all was okay except that it gives a warning on install that it wants node.js v4.50 so that may need to become a requirement (?)
![image](https://user-images.githubusercontent.com/20369477/32018480-ebd3e6e0-b9c1-11e7-8e1e-69cb28be8363.png)

I then loaded 1.5 (latest release) and it went smoother than last evening 
The only difference is that I created the settings.jon file before the 

> npm install --production

 and then 

> npm start

I then tried rel 1.5 with node.js v 6.11.4 and it generated errors similar to what was reported in 552 but the api was still operational

I'll keep checking over the next few days but I'd say as long as you use node v 4.5 you should be good

**Comment by rafale77** [comment]
@autofrank , Any reason why you are running 4.0.0? I have not seen any of these problems and the repo requires >4.5 to begin with. I am running on 4.8 and am not seeing any warning.

**Comment by jishi** [comment]
Is this still an issue?

**Comment by autofrank** [comment]
Hi JImmy
This issue was resolved with a re install
Also I've been running 1.5 for the last two weeks and the TTS/Say is
working consistently with none being cut off early

Thanks for resolving
_af
