### ISSUE TITLE
Add url hook configuration

### ISSUE THREAD

**Issue by jishi** [jishi/node-sonos-http-api#57]
Add an optional configuration parameter that would receive a JSON state object for common changes. 

Maybe additionally have global and optional room filtered url hooks. 

Please subscribe and comment if you are interested in this, and describe your use case if possible.

**Comment by ppitkin** [comment]
Can you elaborate a bit more on what you would propose these functions to deliver and be used for.

 

e.g. what are filtered url hooks and where might one use them?

 

thx

**Comment by jishi** [comment]
Main purpose is for home automation systems, where it can push state changes instead of relying on polling. Most system have some sort of support for it, as far as I can tell.

Another scenario would be where you want to update a public web site with now playing info or similiar, or if you have some signage software running that would allow a similar setup. 

This could of course be handled with websockets too, but I believe the support for that is less common.

**Comment by matiasgarciaisaia** [comment]
So the idea is that node-sonos-http-api will POST to an external webservice each time some event occurs, so the external service can _do things_ about that?

**Comment by ppitkin** [comment]
Good – this is exactly the sort of thing I need to start integrating.

 

I use a universal-Devices ISY994 as my Home automation controller and they have just come out with a new concept of “ISY Nodes” which will allow the integration of just about anything allowing it to look and behave like an ISTEON or ZWave device. I would love to integrate your module into a “node” so that Sonos devices appear directly in the ISY.

 

Attached is their draft spec and it can also be downloaded from here (http://www.universal-devices.com/developers/wsdk/5.0.0/ISY-WS-SDK-Node-Server.pdf) 

 

Regards

Peter

**Comment by jishi** [comment]
Implemented first draft with support for transport-state and topology-change.
