### ISSUE TITLE
Anyway to send player status to IFTTT Webhook?

### ISSUE THREAD

**Issue by psmith3** [jishi/node-sonos-http-api#579]
Jishi, I have been researching if there I anyway to send a webhook to IFTTT when a player is playing and another when it is not. Is there anything you can think of that would accomplish it? I looked at Bronos, but that looks one way from IFTTT to broker.bronos.net only. 

For the my application, to be specific, I am wanting to send a webhook to IFTTT when a specific zone player is playing and then in turn, have IFTTT send a message to my ISY994i to light up a keypad button indicating the player is playing. This is the same button that when turned on, sends a local command to my node-sonos-http-api that starts a favorite in the zone. Any ideas how I could accomplish this? Would be awesome to just send a message straight from node-sonos to my local ISY994i.

**Comment by jishi** [comment]
the http api can trigger a webhook, but you register an endpoint that will receive all events which might not be suitable for you. It was experimental, and there are some ideas about how to improve the usability on it.

However, for today, the receiving end needs to both filter on what kind of event it is, and also for which zone. If you can do that in ISY994i then you should be set, otherwise you would need to build some simple webhook receiver (basically a single file node.js application or whatever you are comfortable with) that would take care of filtering, and also possibly transforming the data to work for your ISY994i system.

https://github.com/jishi/node-sonos-http-api/blob/master/test_endpoint.js is my test implementation of a webhook receiver that just prints out the requests, maybe you can work from that. Also see https://github.com/jishi/node-sonos-http-api/blob/master/README.md#webhook for information about the webhook.

**Comment by psmith3** [comment]
Thank you sir. I figured the receiver would have to filter out the zone player and the event. I will investigate further.

**Comment by psmith3** [comment]
Update on my findings... in my setup, I run Docker on a Snology NAS and have node-sonos-http-api running in Docker too. I now have Webhook running in another Docker Container and through help from that project, I was able to parse and filter the Webhook stream coming from node-sonis and run a local cURL script for when the Kitchen Player is playing and then light a light on my Insteon Keypad that indicates it is playing. The same button on the insteon keypad can also be pressed to send a command to node-sonos to start playing a preset too. Webhook runs another cURL command when the playerState is in playerpaused or Stopped. More info on that thread here. https://github.com/adnanh/webhook/issues/213
