### ISSUE TITLE
Upgrade to latest build but wont startup

### ISSUE THREAD

**Issue by wadoline** [jishi/node-sonos-http-api#58]
Hi,

My raspi was working well with sonos till now.

Today I upgraded the node and node-sonos-http-api and I have the following errors:

1.-The server doesn´t autostart. I followed this steps in issue #20 and #44, without success
2.- If I run node server.js I have "no settings file found, will only use default settings"

This is my node -v: v0.12.1

Could you help me?

Best regards

**Comment by jishi** [comment]
I have tried to reproduce this but to no avail. How did you install node.js? Could you please try and replace it with this version and let me know if that works? I tried his pre-compiled version of 0.12.1 as well and it still worked.

http://conoroneill.net/node-v0122-for-arm-v6v7-including-raspberry-pi-raspberry-pi-2-and-odroid-c1

**Comment by wadoline** [comment]
Hi jishi

I was busy last month. I will try to reinstall everything again and tell you if it works, including the the 0.12.2

Best regards

**Comment by wadoline** [comment]
Fresh install of raspian
Fresh install of pre-compiled version of node.js
Fresh install of lastest node-sonos-http-api

But I have the same issue, this is the steps for autostart:
$ sudo npm install -g pm2
$ pm2 startup raspberry
$ sudo env PATH=$PATH:/usr/local/bin pm2 startup raspberry -u pi
$ cd /node-sonos-http-api-master
$ pm2 start server.js -x --name "http-api"
$ pm2 dump

If I run node server.js I have "no settings file found, will only use default settings"

Best regards

**Comment by jishi** [comment]
Could you please provide the following in order to identify what happens during discovery:

make sure tcpdump is installed, otherwise install it using "apt-get install tcpdump"

invoke:

    tcpdump -w dump.pcap

in another shell (using screen, tmux or a second SSH session, whatever is more comfortable), try starting the sonos http api without pm2:

    node server.js

let it run for 10-15 seconds, then stop it (Ctrl + C) and then stop tcpdump as well (Ctrl + C). Email me the dump.pcap file to jimmy@shimizu.se

**Comment by wadoline** [comment]
Yes, email sent to you ;)

**Comment by jishi** [comment]
Please try using latest node 4.x.x. Re-open if still a problem.
