### ISSUE TITLE
JSON for State doesn't contain equalizer values in response.

### ISSUE THREAD

**Issue by gtilles** [jishi/node-sonos-http-api#598]
The example for state json show these values but they are not in my response.
"equalizer": {
    "bass": 0,
    "treble": 0,
    "loudness": true

Are they no longer available or am I missing something?

![untitled](https://user-images.githubusercontent.com/36808330/36638601-348f8d0c-19ae-11e8-9aa5-cff37591cb05.jpg)

**Comment by jishi** [comment]
Which version are you running? This was a late add on.

On Feb 25, 2018 07:01, "gtilles" <notifications@github.com> wrote:

The example for state json show these values but they are not in my
response.
"equalizer": {
"bass": 0,
"treble": 0,
"loudness": true

Are they no longer available?

[image: untitled]
<https://user-images.githubusercontent.com/36808330/36638601-348f8d0c-19ae-11e8-9aa5-cff37591cb05.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jishi/node-sonos-http-api/issues/598>, or mute the
thread

**Comment by gtilles** [comment]
C:\sonos>npm start
> sonos-http-api@0.19.0 start C:\sonos
> node server.js

**Comment by gtilles** [comment]
ok, my mistake I installed the latest version. All good
C:\sonos>npm start
> sonos-http-api@1.6.0 start C:\sonos
> node server.js
