### ISSUE TITLE
Enable/disable Sonos:One microphone (Alexa)

### ISSUE THREAD

**Issue by hometm** [jishi/node-sonos-http-api#601]
Hi, 
would it be possible to implement the enable/disable switch for the Sonos:One built-in microphone?

**Comment by jishi** [comment]
I don't know, I don't own a One so I'm not sure where those commands go. If anyone owns a One and can provide me with wireshark dumps for these actions, I would be able to assert if it's possible. 

It might show up in the UPnP spec too, haven't checked that since the introduced this player. But that is trickier to figure out the raw protocol from, having a dump is much easier.

**Comment by hometm** [comment]
After a short discussion with Sonos, I got the answer:
Up to now, enabling/disabling the microphone is not possible per App or API. They mentioned, that this could be possible in a further version of the firmware.
