### ISSUE TITLE
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by Heursqem** [jishi/node-sonos-http-api#638]
Hi

I did a clean install on RPI, Domoticz being supported by this Sonos HTTP api.
Using PM2 to manage starting/stopping the api. 

I am able to get it working but with every call I get error message:
`(node:9065) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

After some time (few hours or maybe some calls) the solution stops working and even my sonos needs a hard reset (power off)

Any help would be appreciated

Cheers
Heursqem

**Comment by jishi** [comment]
Hi, that warning shouldn't affect anything, it's just a deprecation warning that happens in Node8+ (since I'm using node 4 compatible code). 

Have you verified that the system doesn't stop working if you aren't running this software? Sounds to me like you have some other issue (network loop or heavy interference) that is causing your system to lockup. 

Is the Pi by any chance connected to any ethernet jack on any of your Sonos players?

**Comment by jishi** [comment]
Re-open if this is still a problem, but it still seems highly unlikely that it is the api that is the culprit
