### ISSUE TITLE
Crossfade proper use?

### ISSUE THREAD

**Issue by tsummerall** [jishi/node-sonos-http-api#64]
Thank you for the fantastic HTTP API! It works really well.

Is there info anywhere about how the crossfade option is supposed to work? If I set it to "on" for the group controller and then I call "favorite" on that controller to switch the currently playing song to a favorite it stops the currently playing song completely before starting the new favorite.

One complicating factor is that I'm trying to do this with a song playing but then switching to a streaming radio station. Maybe that's not supported?

Because the Sonos alarm doesn't let you adjust the fade up time I hacked a fade-up function today using the http API you created that works very well, but I have no idea how to manually hack a crossfade or if it's possible.

**Comment by jishi** [comment]
Hi, I'm not sure I understand what the problem is? When you activate a favorite, it is supposed to stop playback and start playing that favorite instead, be it a single song, a playlist or a radio station. What is it that you expect?

Or did you expect a crossfade switch to a new favorite? I see. Well, crossfade is the builtin crossfade option in Sonos, and I think it will only crossfade between tracks in queue (and maybe for radiostations that utilizes the avtransport queue), so what you try to achieve is not possible. You could manually do a fade out/fade in feature, but it would be impossible to do a crossfade in that regard since you can't mix different sources manually.
