### ISSUE TITLE
VoiceRSS not playing

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#682]
Recently my TTS hasn't been working.  I had to reactivate my voicerss account, which I did and I generated a new api key.  I change the settings.json file and restarted the docker.  However, when I am trying to test it, the speaker stops the music it is playing like it is going to say the phrase command but it doesn't,  Sonos gives me an error that it can't play the song.  The command was 192.168.1.100:5005/Kitchen Sonos/say/Hello

Here is the log:

2019-03-06T13:52:12.253Z INFO Presets loaded: { Dogs:
{ players:
[ { roomName: 'Kitchen Sonos', volume: 17 },
{ roomName: 'Master Sonos', volume: 16 },
{ roomName: 'Laurens Sonos', volume: 16 },
{ roomName: 'Workout Room', volume: 18 },
{ roomName: 'Ryans Sonos', volume: 18 } ],
pauseOthers: false,
favorite: 'Q107' },
Jane:
{ players:
[ { roomName: 'Kitchen Sonos', volume: 15 },
{ roomName: 'Master Sonos', volume: 15 },
{ roomName: 'Laurens Sonos', volume: 15 },
{ roomName: 'Ryans Sonos', volume: 15 } ],
playMode: { shuffle: true, repeat: 'all', crossfade: true },
pauseOthers: false,
playlist: 'Classic Acoustic' },
speakers:
{ speakers:
{ players:
[ { roomName: 'Kitchen Sonos', volume: 35 },
{ roomName: 'Master Sonos', volume: 35 },
{ roomName: 'Laurens Sonos', volume: 35 },
{ roomName: 'Ryans Sonos', volume: 35 },
{ roomName: 'Workout Room', volume: 35 } ],
pauseOthers: false } } }
2019-03-06T13:52:12.900Z INFO http server listening on 0.0.0.0 port 5005
2019-03-06T13:58:37.500Z ERROR
Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
at Object.invoke (/app/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
at Player.setAVTransport (/app/node_modules/sonos-discovery/lib/models/Player.js:727:15)
at promise.then (/app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:128:46)
at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2019-03-06T13:58:37.608Z ERROR
Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
at Object.invoke (/app/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
at Player.setAVTransport (/app/node_modules/sonos-discovery/lib/models/Player.js:727:15)
at promise.then (/app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:128:46)
at process._tickDomainCallback (internal/process/next_tick.js:135:7)
announce file for phrase "Hello" does not seem to exist, downloading

**Comment by jishi** [comment]
Try finding the cached voice file and open it in a texteditor. If voicerss
gives you an error message, it will tell you in that file.

**Comment by pcgirl** [comment]
Thanks for getting back to me.  I don't know where to find the cached voice file.  When I send the command http://192.168.1.100:5005/Kitchen Sonos/say/Hello I get this error:

error   "Got status 500 when invoking /MediaRenderer/AVTransport/Control"
stack   "Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n at Object.invoke (/app/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n at Player.setAVTransport (/app/node_modules/sonos-discovery/lib/models/Player.js:727:15)\n at promise.then (/app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:128:46)\n at process._tickDomainCallback (internal/process/next_tick.js:135:7)"


Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

________________________________

**Comment by pcgirl** [comment]
Then I tried it again a couple of times and it said success but it didn't speak through the speaker.

Thanks,
Jane Johnson

++++++++++++++++++

________________________________

**Comment by jishi** [comment]
Normally it creates a folder called `cache` at the same level as server.js, but if you run this through docker you have probably mapped that to somewhere else.

**Comment by pcgirl** [comment]
I did see that and I checked that directory but nothing is in there.

Thanks,

Jane Johnson

On Mar 11, 2019, at 9:28 AM, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:


Normally it creates a folder called cache at the same level as server.js, but if you run this through docker you have probably mapped that to somewhere else.

**Comment by hastionz** [comment]
I also recently had to reactivate my voicerss account, and then found out it wasn't working. After some digging I realised that voicerss was returning a .wav file, rather than a .mp3 file. Not that Windows bothered to mention it, although it had a .mp3 extension(thanks Windows!). I checked the voicerss site documentation, and .wav format is the default - I presume this must have changed recently.

I was able to fix it  by editing the "ttsRequestUrl" parameter in "try-download-tts.js", adding "c=MP3" to specify mp3 files:

    const ttsRequestUrl = `http://api.voicerss.org/?key=${settings.voicerss}&f=22khz_16bit_mono&**c=MP3**&hl=${language}&src=${phrase}`;

It's working OK since. I did have to restart the node.js service to get it to pick up the changes in the configuration, and might have needed to delete the cached audio files as well to ensure that it downloaded a new copy.

**Comment by pcgirl** [comment]
This is very helpful!  Do you put in the ** as well?

**Comment by hastionz** [comment]
I didn't add the double asterisks - I think they were inserted by Github's markup, but then not displayed? Anyway, edited them out of the previous comment to prevent confusion.

**Comment by pcgirl** [comment]
OK, thanks!  I actually had to add this into the voicers.js file which was located in the tts-providers directory.  It wasn’t in the try-download-tts.js file but this helped me find it.

**Comment by pcgirl** [comment]
This is still not working.  Sometimes I get an error and sometimes it says success but nothing plays.  I am just using a simple command to test.  http://192.168.1.100:5005/Kitchen Sonos/say/Goodbye




status  "error"
error   "Got status 500 when invoking /MediaRenderer/AVTransport/Control"
stack   "Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n at Object.invoke (/app/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n at Player.setAVTransport (/app/node_modules/sonos-discovery/lib/models/Player.js:727:15)\n at promise.then (/app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:128:46)\n at process._tickDomainCallback (internal/process/next_tick.js:135:7)"


Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

________________________________

**Comment by pcgirl** [comment]
I couldn't get this working on my docker, so I stopped it on there and restarted it on my windows 7 machine.  It seems to work on there.  Might be something wrong in the latest docker update.

**Comment by hastionz** [comment]
Seems like you might have a slightly different issue than me then - especially given the different location of the config. I haven't tried the docker install, so I can't comment on any specifics.
If you want to carry on trying to fix i though, I'd recommend trying to find the .mp3 files that the voicerss service creates - that helped me to troubleshoot the issue. When I opened one of the working files in notepad, I could see that it started with an ID3 tag, and was encoded by "Lavf54.21.100". When I opened one of the broken files, it contained the word "WAVEfmt" right at the top of the file indicating that it was a .wav file rather than a .mp3. You can also test that the audio files are being served up correctly, by hitting the API with /tts/<mp3_file_name> after the domain & port (so "http://192.168.1.100:5005/tts/test_file.mp3" for example, although the voicerss filename are long alphanumeric strings rather than anything useful). Bear in mind though that browsers seem to be less fussy, and will happily play .wav files with a .mp3 extension that seem to confuse Sonos.

**Comment by jishi** [comment]
@pcgirl Given your stack trace, it seems to struggle with breaking out the player that you want to announce on. It also tells me that it sends the request to the player, but the player returns with an error. 

Is there any specific group states that are more error prone than others? If it fails, will it just as well work on a second attempt (with no real changes made)?

**Comment by pcgirl** [comment]
I haven’t tried it lately as it wasn’t working.  I have seen this https://github.com/jishi/node-sonos-http-api/pull/687/commits/7fc74e8f46c341f2458626b3ab392ea671255db8 and added the &c=MP3 to the line.  I will test it more this weekend and get back to you.  I would really like to get this working again.  Worked really well and then all of a sudden it wasn’t working anymore.

Thanks for getting back to me on this!

Jane

**Comment by pcgirl** [comment]
I just tested the command to speak on just the one speaker in the Kitchen.  http://192.168.1.100:5005/Kitchen Sonos/say/Goodbye and the webpage comes as success and the speakers stops play but doesn't say anything but then it resumes what it was playing.  And there are no errors in the log.  It doesn't say that it downloaded the text or anything.

**Comment by jishi** [comment]
did you clear out any potentially cached rss files? Or tried with a competely unique phrase? Because the files are cached based on language/voice/phrase hash, meaning that if it previously downloaded a "faulty" WAV file it will continue to use that. 

The cached files are under `static/tts` wherever the app is installed. for the docker file I would assume it would be `/app/static/tts`.

**Comment by pcgirl** [comment]
Thanks, I cleared out the files in the static/tts directory.  Let's see how things go.

Thanks,
Jane
________________________________

**Comment by pcgirl** [comment]
The TTS seems to be coming through now but when I look in the log there

Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

________________________________
