### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by svenerbe** [jishi/node-sonos-http-api#683]
Hi, i try to run node-sonos-http-api on a kubernetes cluster. The app is working but the discovery don't found any speaker. it is possible to configure a specific subnet for the discovery? In the docker container i have the following nic config.

/app $ ifconfig -a
eth0      Link encap:Ethernet  HWaddr 86:2F:5B:CB:68:0D
          inet addr:10.36.0.2  Bcast:10.47.255.255  Mask:255.240.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1376  Metric:1
          RX packets:59954 errors:0 dropped:0 overruns:0 frame:0
          TX packets:57976 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:10802026 (10.3 MiB)  TX bytes:10122157 (9.6 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

The Sonos player are in the subnet 192.168.178.* The subnet of the player are reachable from the docker container. Any idea?

**Comment by jishi** [comment]
This is because it uses multicast/broadcast to find the players. Even
though unicast traffic works, doesn't mean that multicast/broadcast does.

I never found a way to forward multicast out of a docker container, the
only solution I could come up with was to run it with host networking. I
don't know if that is possible on kubernetes, I have no experience with it.
If you can get either multicast or broadcast traffic to forward out to the
host network, it should work to find them, but you also have events traffic
that are http requests and the endpoint needs to be sent to the players.
That won't fly behind a NAT either.
