### ISSUE TITLE
npm stop

### ISSUE THREAD

**Issue by 0rTiN** [jishi/node-sonos-http-api#694]
Hi,
I am using your create code to control my Sonos stuff over my home automation system. Sometime it is necessary to stop the server. I do this simply by grepping the pid and kill it. In this case get an error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 143
npm ERR! sonos-http-api@1.6.8 start: `node server.js`
npm ERR! Exit status 143
npm ERR!
npm ERR! Failed at the sonos-http-api@1.6.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-14T20_59_51_946Z-debug.log

```
Is there a more gentle way to stop the server? "NPM stop" is not available...

**Comment by jishi** [comment]
You should be able to send a SIGINT instead of the default SIGTERM for a more graceful quit. Look at the `kill` documentation to see how you do that for your platform.

The npm start is not a daemonization, there are other tools for that (pm2 being one that I personally prefer). A daemon runner would solve this automatically.
