### ISSUE TITLE
Start Clip from preset

### ISSUE THREAD

**Issue by FrederikM1988** [jishi/node-sonos-http-api#738]
Hi guys,

is it possible to start a clip from a json-preset?
Like:

```
{
  "players": [
    { "roomName": "Schlafzimmer", "volume": 80},
    {"roomName": "Küche", "volume": 80}
  ],
  {"command":"clip" , "uri": "alarm.mp3"}
}
```

i think this is wrong, but i dont find a example in the documentation.

**Comment by jishi** [comment]
There is no clip support for presets since it wasn't really the use case for a preset. You can use a preset without any action and a paused state, followed by a clip command, or you can provide a preset with the clip command if you only want to use the grouping/volume, using the `clippreset` action. the documentation is sparse on it, but you can look at https://github.com/jishi/node-sonos-http-api/issues/426#issuecomment-337385754 for reference.
