### ISSUE TITLE
Unable to run as docker instance

### ISSUE THREAD

**Issue by riemers** [jishi/node-sonos-http-api#80]
Perhaps the only thing i need to know is what ports need to be open? UDP 1901 and TCP 5005 to start of with, are there more? But i get the same error message as issue #60 , have a synology NAS which can run these nice little 'projects' as docker containers.

I've placed the container at https://hub.docker.com/r/riemers/sonos_http_api/ , when its working i can also PR the Dockerfile / .sh file i used. It always grabs the git repo before starting up, so its always the latest.

**Comment by jishi** [comment]
The application requires, in addition to the ports you are mentioning, also inbound connections on port 3500. If this is taken, it will use port 3501, 3502 etc until it finds an available port. This will not be an issue with Docker though, since it will be isolated.

It also requires outbound udp multicast traffic, to destination 239.255.255.250 (on port 1900), and the returning traffic (which would be udp 1901, I think this is unicast). The multicast might be a problem, I'm not sure if that would be possible to specify in docker.

**Comment by riemers** [comment]
I'll just give it a go tonight, since its ideal for a docker.. will let you know.

**Comment by riemers** [comment]
I've not got it working in a docker just yet.. but if it cannot find anything and you go to /zones for example it will just stop the program. It would be better if it would give some log feedback but remain online instead. Trying to install docker locally, but only have windows here so its not so straightforward ;p

Also your /docs points to a swagger installation which assumes your commands are at /sonos/xxxx which i believe by default is / instead.

**Comment by jishi** [comment]
Yeah, I just haven't gotten around to fixing that yet. But it's a safe bet to assume that it is the multicast that is the culprit here. I assume that you are using boot2docker in virtualbox for your test now? This adds even more complexity to the setup, since you will be NAT:ing your virtual machine as well (on top of docker NAT). A good start is to just use bridge network in virtualbox, but then you need to adjust the docker tools to access your virtual box instance at the dynamic local IP that it will receive instead of 192.168.99.100 which I believe is the default.

I wasn't aware of the documentation issue though, will look into it.

**Comment by jishi** [comment]
Looking at the docker documentation, seems like running the Docker container with --net=host would bypass the NAT altogether, which probably would solve your issue. Maybe give that a try? Might not be desirable though, but you could rule out any external factors like virtualbox with this.

**Comment by jishi** [comment]
And here is an interesting discussion on this topic:
https://github.com/docker/docker/issues/3043

**Comment by riemers** [comment]
with the --net=host it does work, but also had some issues, but that was because of a typo in the new code it seems. Anyways , here is the PR https://github.com/jishi/node-sonos-http-api/pull/83 and i'll close this ticket.
