### ISSUE TITLE
Can't get PlayMode in a preset working

### ISSUE THREAD

**Issue by leerich** [jishi/node-sonos-http-api#81]
I'd like to turn on shuffle, repeat and crossfade in a preset.  Nothing seems to work.  Even the example with just shuffle doesn't work, unless the zone already had shuffle turned on.  I'm not sure if my syntax is wrong.  I've tried:

 "playMode": {
    "shuffle": true,
    "crossfade": true,
    "repeat": true
    },

as well as:

  "playMode": "CROSSFADE",

but haven't had any luck.   Hoping someone can give me a hint.

Thank you.

**Comment by jishi** [comment]
By looking at the code the playMode property only allows for the UPnP modes which consists of:

"NORMAL", "REPEAT_ALL", "SHUFFLE_NOREPEAT", "SHUFFLE"

The crossfade is a separate function, and is not supported today. I will probably rewrite it to follow the first syntax that you used, since that makes much more sense.

**Comment by jishi** [comment]
I created a ticket in the discovery project. Please follow that if you want to track progress.

https://github.com/jishi/node-sonos-discovery/issues/44

**Comment by leerich** [comment]
Thanks Jishi!
