### ISSUE TITLE
presets.json

### ISSUE THREAD

**Issue by Heursqem** [jishi/node-sonos-http-api#92]
Hi

I have a question, not an issue. Don't know if this is the right place, but did not find any other possibility to ask....

I would like to
1* buffer / remember active state of all my rooms/players
2* put all players on mute
3* play 1 sound in one of my rooms
4* go back to starting state, the one buffered at #1 

Would this be possible?

thanks a lot!

**Comment by jishi** [comment]
Hm... well, sure, anything is possible. Basically you want to do what the sayAll command does, but only for one speaker? This can be a bit tricky, I haven't yet perfected this since you need to do a lot of waiting for the correct state of your players to apply, before you continue on each step. This make the success a bit intermittent. Does this answer your question?

**Comment by Heursqem** [comment]
thanks jishi

let me put the question different

How can I create one single script, doing the following for 1 player

1. buffer current state
2. play a sound or a song or one of the presets
3. go back to initial state (as buffered at the start at line #1)

Would this be possible?

**Comment by jishi** [comment]
I have tried to do something similar with the say and sayAll commands, but there are some timing issues that I haven't been able to resolve yet. You can look at that for inspiration. If you can live with a non-exact return to the buffered current state, it is fairly simple to achieve since the preset can both take an uri to play, as well as track no in queue and elapsed time (IIRC).

**Comment by Heursqem** [comment]
ok, now I understand you answer, thanks for that!

My challenge - I am not able to write JS code. Could you help? I can live very well with a non-exact return to the buffered current state, no problem with that

Also, taking only one player into scope would be enough. No worries about the other players.

Could you give me some support on this?

**Comment by jishi** [comment]
Unfortunately I must put my efforts on improving other stuff on this. I'm closing this issue since I can't give you more info than this. I will probably implement the possibility to play custom mp3-files that might be what you are looking for, follow issue #136 if you want to keep track of status.
