### ISSUE TITLE
Running on Synology Diskstation 214play?

### ISSUE THREAD

**Issue by kammmuschel** [jishi/node-sonos-http-api#99]
I am running node-sonos-http-api on my Windows PC with Node.js version 4.2.3 LTS - no problem, everything works.

But I want to install it on my Synology Diskstation 214 play, DSM 5.2-5644 Update 1. There is a package for Node.js which I have installed (version 0.12.6-0112). I can run "npm install --production", but when I try to run "npm start" I get the following output. Is that a known issue, is anyone running node-sonos-htto-api on a Synology?

> sonos-http-api@0.17.0 start /volume1/node-sonos-http-api-master
> node server.js

/volume1/node-sonos-http-api-master/node_modules/sonos-discovery/lib/player.js:2                         59
      .then((highResAlbumArtUrl) => {
                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/volume1/node-sonos-http-api-master/node_modules/sono                         s-discovery/lib/sonos.js:11:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 3.2.40
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.17.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@0.17.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /volume1/node-sonos-http-api-master/npm-debug.log

Best Regards,
Daniel

**Comment by jishi** [comment]
Hi, this is due to the fact that my latest update requires node 4.x.x because of some syntatical changes. There are pre-compiled ARM versions of node 4 available, but seems like the synology community hasn't yet packaged them. However, the DS214Play seem to be using a x86 CPU? 

You have two options as I see it:

Upgrade node.js on your NAS manually, basically replacing the node and npm binary in the filesystem with the versions that are available for x86. There must be other people that are trying to do the same, I suggest reaching out to the user forums for synology. 

OR, downgrade the sonos-discovery package. Basically, in the file package.json, change the version in the url for node-sonos-discovery to 0.15.7. This will not be a long term solution if you want to keep up to date with the api, but it's an easy fix for now. 

It's to much work to maintain different versions for older node.js, and I want to make use of the new features that are native in node 4. Sorry about the inconvenience!

**Comment by kammmuschel** [comment]
Thanks a lot for the immediate answer :)

Unfortunately I cannot find any good input from the community on this. But I have replaced now the binaries with the ones from this package: https://nodejs.org/dist/v4.2.3/node-v4.2.3-linux-x86.tar.gz

It seems to work, "npm version" now gives "... node: 4.2.3... " BUT: When I run "npm start" it runs longer than earlier, so far so good. But then I get this:

> sonos-http-api@0.17.0 start /volume1/node-sonos-http-api-master
> node server.js

no settings file found, will only use default settings
module.js:339
    throw err;
    ^

Error: Cannot find module '/volume1/node-sonos-http-api-master/lib/actions/'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at requirePath (/volume1/node-sonos-http-api-master/node_modules/require-fu/lib/index.js:14:22)
    at /volume1/node-sonos-http-api-master/node_modules/require-fu/lib/index.js:21:9
    at Array.forEach (native)
    at fuDirectory (/volume1/node-sonos-http-api-master/node_modules/require-fu/lib/index.js:20:34)
    at /volume1/node-sonos-http-api-master/node_modules/require-fu/lib/index.js:25:5
    at new HttpAPI (/volume1/node-sonos-http-api-master/lib/sonos-http-api.js:36:24)
    at Object.<anonymous> (/volume1/node-sonos-http-api-master/server.js:40:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

npm ERR! Linux 3.2.40
npm ERR! argv "/volume1/@appstore/Node.js/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.2.3
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.17.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@0.17.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /volume1/node-sonos-http-api-master/npm-debug.log


npm-debug.log:
=============

0 info it worked if it ends with ok
1 verbose cli [ '/volume1/@appstore/Node.js/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.11.2
3 info using node@v4.2.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sonos-http-api@0.17.0
6 info start sonos-http-api@0.17.0
7 verbose unsafe-perm in lifecycle true
8 info sonos-http-api@0.17.0 Failed to exec start script
9 verbose stack Error: sonos-http-api@0.17.0 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/volume1/@appstore/Node.js/usr/
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/volume1/@appstore/Node.js/usr/
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proce
10 verbose pkgid sonos-http-api@0.17.0
11 verbose cwd /volume1/node-sonos-http-api-master
12 error Linux 3.2.40
13 error argv "/volume1/@appstore/Node.js/usr/bin/node" "/usr/bin/npm" "start"
14 error node v4.2.3
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error sonos-http-api@0.17.0 start: `node server.js`
17 error Exit status 1
18 error Failed at the sonos-http-api@0.17.0 start script 'node server.js'.
18 error This is most likely a problem with the sonos-http-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls sonos-http-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by jishi** [comment]
Hm, I have got report from others with the same issue: https://github.com/jishi/node-sonos-http-api/issues/55

We never really got to the bottom of it, and I ran out of ideas. For some reason, it seem to find "empty" file entries that it tries to load. Why that is, I don't know. What happens when you actually stand in the correct folder, and run just:

node server.js

?

**Comment by kammmuschel** [comment]
exactly the same :(

**Comment by kammmuschel** [comment]
Now I have tried the workaround to use the old node-sonos-discovery to 0.15.7, but with the Synology Node.js package. This resolves the initial error I got, but it ends up with the same error I get after I had replaced the Node.js binaries. So both ways end up in the same dead end. I think I give up and install it on a Raspberry instead :-( But again thank you for your help!

**Comment by jishi** [comment]
If you can manage to backtrace why it tries to load paths that don't exists, that would be super. It somehow seems like the package requireFu doesn't resolve filenames correctly in the synology version of Linux, which is very odd. However, there was one guy that got the same issue on a raspberry pi as well, so it might not have been related to synology at all https://github.com/jishi/node-sonos-http-api/issues/39 but as I said, I can't reproduce it.

**Comment by kammmuschel** [comment]
I have now installed it on a raspberry. It is working perfectly, so it must have been related to Synology. Maybe the file structure there, not sure.

**Comment by libatiba** [comment]
**Error: Cannot find module '/.../lib/actions/' on Synology-NAS**
On Synology DS415+ I figured out, that the problem "Error: Cannot find module '/.../node-sonos-http/lib/actions/' at Function.Module._resolveFilename (module.js...)" is caused by hidden directories that are created by an indexing service of the NAS. The .js-module tries to enumerate all files in a directory - but on Synology hidden subdirectories cause the routine to fail. The directories start with the @-sign e.g. @eaDir. Deleting the directory (and subdirectories) solved my problems completely!

**Comment by jishi** [comment]
@libatiba that's a great find! Could you please file a new issue with
details so I can make a workaround for it?

**Comment by libatiba** [comment]
Dear Jimmy,
As my yesterdays comment was my first use of github (other than downloading), I would prefer to give you the details via email an let you decide how to fix it (I don’t know how to file issues ;-)


I did a little more testing…
The problem arrises in general when the lib/actions-folder contains a subdirectory that contains a file. An empty subdirectory does not provoke the error.
So it’s very easy for you to reproduce the error: just create a directory „test“ in lib/actions and copy a file into this folder.


On Synology Disk Station hidden folders are created by an indexing service. Every directory has a subdirectory named „@eaDir“ containing an index file for every file and folder with the naming convention: filename@SynoEAStream or foldername@SynoEAStream
These folders are always recreated when new files are copied in the directories. The @-sign at the beginnen of a folder-name does not generally hides them from the user. Only @eaDir -folders are hidden. If I rename the folder (on a ssh-Shell)
 to @eaTir (D->T) then the file is visible.  (I’m not a unix-professional - so I don’t now the mechanism how they do the hiding…) But your javascript sees them and the error ist caused. (on the ssh-Shell the ls-command shows the files, but any access to the
 directory with smb (Windows-Share) or afp (Apple, OSX) hides the directory)


From my understanding the error is caused in the file nodemodules/require-fu/lib/index.js  in function requirePath
(but I’m no javascript-expert too!)


In my opinion there are two ways to prevent the error:
1. prevent subdirectory search when enumerating objects in /lib/actions (no problem as long as never subdirectories are needed)
2. filter any subdirectories starting with the @-sign (It’s the synology-way of hiding files - if I remember correct it must not only be @eaDir but also @tmp, @ssbackup…)




Following is the output from my terminal (line numbers must not be correct since I added some console.log-entries to trace down the error)

> sonos-http-api@0.18.1 start /volume1/Data/node-sonos-http
> node server.js


no settings file found, will ooonly use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from bond0
info: discovering all IPs from ppp300
info: relevant IPs 192.168.0.90=null, 10.2.0.0=null
Listening on
http://localhost:5007/
module.js:341
    throw err;
    ^



Error: Cannot find module '/volume1/Data/node-sonos-http/lib/actions/'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requirePath (/volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:24:22)
    at /volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:36:9
    at Array.forEach (native)
    at fuDirectory (/volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:33:34)
    at /volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:40:5
    at new HttpAPI (/volume1/Data/node-sonos-http/lib/sonos-http-api.js:42:24)
    at Object.<anonymous> (/volume1/Data/node-sonos-http/server.js:51:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)



npm

ERR! Linux 3.10.35
npm

ERR! 
argv "/usr/local/n/versions/node/5.8.0/bin/node" "/usr/local/n/versions/node/5.8.0/bin/npm" "start"
npm

ERR! 
node v5.8.0
npm

ERR! 
npm  v3.7.3
npm

ERR! 
code ELIFECYCLE
npm

ERR! sonos-http-api@0.18.1 start: `node server.js`
npm

ERR! Exit status 1

npm
ERR! 
npm

ERR! Failed at the sonos-http-api@0.18.1 start script 'node server.js'.
npm

ERR! Make sure you have the latest version of node.js and npm installed.
npm

ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm

ERR! not with npm itself.
npm

ERR! Tell the author that this fails on your system:
npm

ERR!     node server.js
npm

ERR! You can get information on how to open an issue for this project with:
npm

ERR!     npm bugs sonos-http-api
npm

ERR! Or if that isn't available, you can get their info via:
npm

ERR!     npm owner ls sonos-http-api
npm

ERR! There is likely additional logging output above.



npm

ERR! Please include the following file with any support request:
npm

ERR!     /volume1/Data/node-sonos-http/npm-debug.log







Hopefully me error-description is detailed enough for you to reproduce, find and fix it!

Thank you for your great work in creating the sonos-http-api!!!

Best regards!

Jörg







___________________________________________________________________

Dr. med. Jörg Tittelbach

Oberarzt

Klinik für Hautkrankheiten

Universitätsklinikum Jena - Bachstrasse 18 - D-07743 Jena 

Die gesetzlichen Pflichtangaben finden Sie unter 
http://www.uniklinikum-jena.de/Pflichtangaben.html




Am 18.03.2016 um 08:55 schrieb Jimmy Shimizu <notifications@github.com>:

@libatiba that's a great find! Could you please file a new issue with
details so I can make a workaround for it?
—
You are receiving this because you were mentioned.
Reply to this email directly or 
view it on GitHub
